///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Lynn_DPI_AT
{
    public partial class ApplyBtn_On_Production
    {
        public const int DIALOG_POLL_INTERVAL_MS = 1000;
        public const int DIALOG_POLL_TIMEOUT_MS = 60000;

        private void Init()
        {
            Report.Log(ReportLevel.Info, "ApplyBtn_On_Production", "Module bat dau.");
        }

        public void ClickApplyWithPolling()
        {
            string dialogPath = "/form[@name='Popup']";
            string applyBtnPath = "/form[@name='Popup']//button[@text='Apply']";

            // --- Chẩn đoán: đếm tất cả form[@name='Popup'] đang tồn tại ---
            try
            {
                IList<Ranorex.Core.Element> allPopups = Host.Local.Find(dialogPath, 0);
                Report.Log(ReportLevel.Info, "ApplyBtn_On_Production",
                    string.Format("CHAN DOAN: Tim thay {0} form[@name='Popup']", allPopups.Count));

                for (int i = 0; i < allPopups.Count; i++)
                {
                    try
                    {
                        var el = allPopups[i];
                        bool vis = el.Visible;
                        var rect = el.ScreenRectangle;
                        Report.Log(ReportLevel.Info, "ApplyBtn_On_Production",
                            string.Format("  Popup[{0}]: Visible={1}, ScreenRect={2}",
                                i, vis, rect));
                    }
                    catch (Exception ex)
                    {
                        Report.Log(ReportLevel.Warn, "ApplyBtn_On_Production",
                            string.Format("  Popup[{0}]: khong doc duoc — {1}", i, ex.Message));
                    }
                }

                if (allPopups.Count > 1)
                {
                    Report.Log(ReportLevel.Warn, "ApplyBtn_On_Production",
                        "CANH BAO: >1 form[@name='Popup'] ton tai! "
                        + "Kiem tra dialog co the KHONG BAO GIO thay 'da dong'. "
                        + "Can dung tin hieu dang tin hon (vd: BtnApplyProductionPresetting.Exists).");
                }
            }
            catch (Exception ex)
            {
                Report.Log(ReportLevel.Warn, "ApplyBtn_On_Production",
                    string.Format("CHAN DOAN: loi khi dem Popup — {0}", ex.Message));
            }

            // --- Vòng poll kiên nhẫn: 60 giây, mỗi 1 giây ---
            Report.Log(ReportLevel.Info, "ApplyBtn_On_Production",
                string.Format("Bat dau polling dialog — toi da {0}s, moi {1}s",
                    DIALOG_POLL_TIMEOUT_MS / 1000, DIALOG_POLL_INTERVAL_MS / 1000));

            var sw = System.Diagnostics.Stopwatch.StartNew();
            int round = 0;
            bool hasClicked = false;

            while (sw.ElapsedMilliseconds < DIALOG_POLL_TIMEOUT_MS)
            {
                round++;

                // Dieu kien 1: Dialog da bien mat?
                bool dialogExists = repo.InspectionRegionSettings.SelfInfo.Exists(0);
                if (!dialogExists)
                {
                    sw.Stop();
                    Report.Log(ReportLevel.Success, "ApplyBtn_On_Production",
                        string.Format("Vong {0}: Dialog da bien mat sau {1:F1}s — THANH CONG"
                            + (hasClicked ? " (da click Apply truoc do)" : " (tu dong dong, khong can click)"),
                            round, sw.ElapsedMilliseconds / 1000.0));
                    return;
                }

                // Dieu kien 2: Apply button ton tai + Visible + Enabled?
                try
                {
                    Ranorex.Core.Element applyEl;
                    bool applyFound = Host.Local.TryFindSingle(applyBtnPath, 0, out applyEl);

                    if (applyFound && applyEl.Visible && applyEl.Enabled)
                    {
                        Report.Log(ReportLevel.Info, "ApplyBtn_On_Production",
                            string.Format("Vong {0}: Apply Visible+Enabled — click 1 phat", round));
                        repo.InspectionRegionSettings.BtnApplyProductionPresetting.Click();
                        hasClicked = true;
                    }
                    else if (applyFound)
                    {
                        Report.Log(ReportLevel.Info, "ApplyBtn_On_Production",
                            string.Format("Vong {0}: Dialog con mo, Apply ton tai nhung chua san sang (Visible={1}, Enabled={2}) — cho tiep",
                                round, applyFound ? applyEl.Visible.ToString() : "N/A",
                                applyFound ? applyEl.Enabled.ToString() : "N/A"));
                    }
                    else
                    {
                        Report.Log(ReportLevel.Info, "ApplyBtn_On_Production",
                            string.Format("Vong {0}: Dialog con mo, Apply KHONG tim thay — cho tiep", round));
                    }
                }
                catch (Exception ex)
                {
                    Report.Log(ReportLevel.Warn, "ApplyBtn_On_Production",
                        string.Format("Vong {0}: Loi khi kiem tra Apply — {1}", round, ex.Message));
                }

                Delay.Milliseconds(DIALOG_POLL_INTERVAL_MS);
            }

            sw.Stop();

            // Het timeout — screenshot va throw
            Report.Log(ReportLevel.Error, "ApplyBtn_On_Production",
                string.Format("THAT BAI: Dialog van con mo sau {0}s ({1} vong poll). hasClicked={2}",
                    DIALOG_POLL_TIMEOUT_MS / 1000, round, hasClicked));

            try
            {
                Report.Screenshot(repo.InspectionRegionSettings.Self, true);
            }
            catch
            {
                try { Report.Screenshot(); } catch { }
            }

            throw new Exception(string.Format(
                "ApplyBtn_On_Production: Dialog 'Production Presetting' van con mo sau {0}s. "
                + "Da click Apply: {1}. Kiem tra app co dang loading qua lau hoac dialog bi treo.",
                DIALOG_POLL_TIMEOUT_MS / 1000, hasClicked));
        }

    }
}
