///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Lynn_DPI_AT
{
    public partial class Login_Pass
    {
        private void Init()
        {
            Report.Log(ReportLevel.Info, "Login",
                string.Format("Login_Pass chay voi user '{0}'.", this.UserName));

            if (repo.CCIMainWindow.SelfInfo.Exists(2000))
            {
                Report.Log(ReportLevel.Success, "Login",
                    "LoginRetry da login thanh cong truoc do. Login_Pass skip login steps.");

                Report.Screenshot(ReportLevel.Info, "Login",
                    "CCIMainWindow da ton tai — skip login.",
                    repo.CCIMainWindow.Self, false);
            }
        }

        public static bool TryLoginWithUser(string user, string pass)
        {
            try
            {
                repo.CCILoginWindow.SelfInfo.WaitForExists(30000);
                Delay.Milliseconds(500);

                TypeIntoUserField(user);
                TypeIntoPasswordField(pass);

                repo.CCILoginWindow.Login.Click("10;8");
                Report.Log(ReportLevel.Info, "Login", "Da click Login. Cho 30 giay de man hinh load...");
                Delay.Milliseconds(3000);

                return IsLoginSuccessful();
            }
            catch (Exception ex)
            {
                Report.Log(ReportLevel.Error, "Login",
                    string.Format("Loi khi thu login voi user '{0}': {1}", user, ex.Message));
                return false;
            }
        }

        private static void TypeIntoUserField(string value)
        {
            repo.CCILoginWindow.XIDPWLoginArea.SomeText.Click("47;2");
            Delay.Milliseconds(500);

            Keyboard.Press("{Home}");
            Delay.Milliseconds(100);
            Keyboard.Press("{Shift down}{End}{Shift up}");
            Delay.Milliseconds(100);
            Keyboard.Press("{Delete}");
            Delay.Milliseconds(200);

            Keyboard.Press(value);
            Delay.Milliseconds(500);

            Report.Log(ReportLevel.Info, "Login",
                string.Format("Da nhap username '{0}'.", value));
        }

        private static void TypeIntoPasswordField(string pass)
        {
            repo.CCILoginWindow.XIDPWLoginArea.XPWWatermark.Click("36;6");
            Delay.Milliseconds(500);

            Keyboard.Press("{Home}");
            Delay.Milliseconds(100);
            Keyboard.Press("{Shift down}{End}{Shift up}");
            Delay.Milliseconds(100);
            Keyboard.Press("{Delete}");
            Delay.Milliseconds(200);

            Keyboard.Press(pass);
            Delay.Milliseconds(200);
        }

        public static void ClearLoginFields()
        {
            if (!repo.CCILoginWindow.SelfInfo.Exists(3000))
                return;

            repo.CCILoginWindow.XIDPWLoginArea.SomeText.Click("47;2");
            Delay.Milliseconds(500);
            Keyboard.Press("{Home}");
            Delay.Milliseconds(100);
            Keyboard.Press("{Shift down}{End}{Shift up}");
            Delay.Milliseconds(100);
            Keyboard.Press("{Delete}");
            Delay.Milliseconds(200);

            repo.CCILoginWindow.XIDPWLoginArea.XPWWatermark.Click("36;6");
            Delay.Milliseconds(500);
            Keyboard.Press("{Home}");
            Delay.Milliseconds(100);
            Keyboard.Press("{Shift down}{End}{Shift up}");
            Delay.Milliseconds(100);
            Keyboard.Press("{Delete}");
            Delay.Milliseconds(200);
        }

        public static bool IsLoginSuccessful()
        {
            return repo.CCIMainWindow.SelfInfo.Exists(40000);
        }
    }
}
