///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Lynn_DPI_AT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login_Pass recording.
    /// </summary>
    [TestModule("d6e58a7d-7478-483b-b95c-a25eb4ef5194", ModuleType.Recording, 1)]
    public partial class Login_Pass : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Lynn_DPI_ATRepository repository.
        /// </summary>
        public static Lynn_DPI_ATRepository repo = Lynn_DPI_ATRepository.Instance;

        static Login_Pass instance = new Login_Pass();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login_Pass()
        {
            UserName = "lynn";
            Password = "1234";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login_Pass Instance
        {
            get { return instance; }
        }

#region Variables

        string _UserName;

        /// <summary>
        /// Gets or sets the value of variable UserName.
        /// </summary>
        [TestVariable("4c09ea2f-1705-48bb-b16a-c64e556da24b")]
        public string UserName
        {
            get { return _UserName; }
            set { _UserName = value; }
        }

        string _Password;

        /// <summary>
        /// Gets or sets the value of variable Password.
        /// </summary>
        [TestVariable("5d4d6c94-2c75-4db3-a680-edf942858962")]
        public string Password
        {
            get { return _Password; }
            set { _Password = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CCILoginWindow.XIDPWLoginArea.SomeText' at 47;2.", repo.CCILoginWindow.XIDPWLoginArea.SomeTextInfo, new RecordItemIndex(0));
            repo.CCILoginWindow.XIDPWLoginArea.SomeText.Click("47;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$UserName'.", new RecordItemIndex(1));
            Keyboard.Press(UserName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CCILoginWindow.XIDPWLoginArea.XPWWatermark' at 36;6.", repo.CCILoginWindow.XIDPWLoginArea.XPWWatermarkInfo, new RecordItemIndex(2));
            repo.CCILoginWindow.XIDPWLoginArea.XPWWatermark.Click("36;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Password'.", new RecordItemIndex(3));
            Keyboard.Press(Password);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CCILoginWindow.Login' at 10;8.", repo.CCILoginWindow.LoginInfo, new RecordItemIndex(4));
            repo.CCILoginWindow.Login.Click("10;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 30s.", new RecordItemIndex(5));
            Delay.Duration(30000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 20s to exist. Associated repository item: 'CCIMainWindow'", repo.CCIMainWindow.SelfInfo, new ActionTimeout(20000), new RecordItemIndex(6));
            repo.CCIMainWindow.SelfInfo.WaitForExists(20000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Create or open recipe.') on item 'CCIMainWindow.CreateOrOpenRecipe'.", repo.CCIMainWindow.CreateOrOpenRecipeInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.CCIMainWindow.CreateOrOpenRecipeInfo, "Text", "Create or open recipe.", null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.Always});
            Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.CCIMainWindow.CreateOrOpenRecipe, false, new RecordItemIndex(8));
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.CCIMainWindow.Self, false, new RecordItemIndex(9));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
