///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Lynn_DPI_AT
{
    public partial class Login_Pass
    {
        private void Init()
        {
            Report.Log(ReportLevel.Info, "Login",
                string.Format("Login_Pass chay voi user '{0}'.", this.UserName));

            if (repo.CCIMainWindow.SelfInfo.Exists(2000))
            {
                Report.Log(ReportLevel.Warn, "Login",
                    "CCIMainWindow da ton tai. LoginRetry co the da login thanh cong truoc do.");
            }
        }

        public static bool TryLoginWithUser(string user, string pass)
        {
            try
            {
                repo.CCILoginWindow.SelfInfo.WaitForExists(30000);
                Delay.Milliseconds(500);

                bool userOk = TypeIntoUserField(user);
                if (!userOk)
                {
                    Report.Log(ReportLevel.Warn, "Login",
                        string.Format("Khong verify duoc username '{0}', tiep tuc login.", user));
                }

                TypeIntoPasswordField(pass);

                repo.CCILoginWindow.Login.Click("10;8");
                Delay.Milliseconds(200);

                return IsLoginSuccessful();
            }
            catch (Exception ex)
            {
                Report.Log(ReportLevel.Error, "Login",
                    string.Format("Loi khi thu login voi user '{0}': {1}", user, ex.Message));
                return false;
            }
        }

        private static bool TypeIntoUserField(string value)
        {
            for (int attempt = 1; attempt <= 3; attempt++)
            {
                repo.CCILoginWindow.XIDPWLoginArea.SomeText.Click("47;2");
                Delay.Milliseconds(500);

                Keyboard.Press("{Home}");
                Delay.Milliseconds(100);
                Keyboard.Press("{Shift down}{End}{Shift up}");
                Delay.Milliseconds(100);
                Keyboard.Press("{Delete}");
                Delay.Milliseconds(200);

                Keyboard.Press(value);
                Delay.Milliseconds(500);

                try
                {
                    string actual = repo.CCILoginWindow.XIDPWLoginArea.SomeText.Element.GetAttributeValueText("Text");

                    if (string.IsNullOrEmpty(actual))
                    {
                        Report.Log(ReportLevel.Info, "Login",
                            string.Format("UserName: GetAttributeValueText tra ve empty, skip verify (attempt {0}).", attempt));
                        return true;
                    }

                    if (actual.Trim() == value.Trim())
                    {
                        Report.Log(ReportLevel.Info, "Login",
                            string.Format("UserName: Verify OK. Expected='{0}', Actual='{1}' (attempt {2}).", value, actual, attempt));
                        return true;
                    }

                    Report.Log(ReportLevel.Warn, "Login",
                        string.Format("UserName: Verify FAILED. Expected='{0}', Actual='{1}' (attempt {2}).", value, actual, attempt));

                    Keyboard.Press("{Escape}");
                    Delay.Milliseconds(300);
                }
                catch (Exception ex)
                {
                    Report.Log(ReportLevel.Warn, "Login",
                        string.Format("UserName: Verify exception: {0}. Skip verify.", ex.Message));
                    return true;
                }
            }

            return false;
        }

        private static void TypeIntoPasswordField(string pass)
        {
            repo.CCILoginWindow.XIDPWLoginArea.XPWWatermark.Click("36;6");
            Delay.Milliseconds(500);

            Keyboard.Press("{Home}");
            Delay.Milliseconds(100);
            Keyboard.Press("{Shift down}{End}{Shift up}");
            Delay.Milliseconds(100);
            Keyboard.Press("{Delete}");
            Delay.Milliseconds(200);

            Keyboard.Press(pass);
            Delay.Milliseconds(200);
        }

        public static void ClearLoginFields()
        {
            if (!repo.CCILoginWindow.SelfInfo.Exists(3000))
                return;

            repo.CCILoginWindow.XIDPWLoginArea.SomeText.Click("47;2");
            Delay.Milliseconds(500);
            Keyboard.Press("{Home}");
            Delay.Milliseconds(100);
            Keyboard.Press("{Shift down}{End}{Shift up}");
            Delay.Milliseconds(100);
            Keyboard.Press("{Delete}");
            Delay.Milliseconds(200);

            repo.CCILoginWindow.XIDPWLoginArea.XPWWatermark.Click("36;6");
            Delay.Milliseconds(500);
            Keyboard.Press("{Home}");
            Delay.Milliseconds(100);
            Keyboard.Press("{Shift down}{End}{Shift up}");
            Delay.Milliseconds(100);
            Keyboard.Press("{Delete}");
            Delay.Milliseconds(200);
        }

        public static bool IsLoginSuccessful()
        {
            return repo.CCIMainWindow.SelfInfo.Exists(20000);
        }
    }
}
