///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Lynn_DPI_AT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Lynn_DPI_ATRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("0ee31be8-b7c0-4867-aed4-3f0533789467")]
    public partial class Lynn_DPI_ATRepository : RepoGenBaseFolder
    {
        static Lynn_DPI_ATRepository instance = new Lynn_DPI_ATRepository();
        Lynn_DPI_ATRepositoryFolders.CCILoginWindowAppFolder _cciloginwindow;
        Lynn_DPI_ATRepositoryFolders.CCIMainWindowAppFolder _ccimainwindow;
        Lynn_DPI_ATRepositoryFolders.InspectionRegionSettingsAppFolder _inspectionregionsettings;
        Lynn_DPI_ATRepositoryFolders.LynnDPIATAppFolder _lynndpiat;
        Lynn_DPI_ATRepositoryFolders.ExplorerAppFolder _explorer;
        Lynn_DPI_ATRepositoryFolders.SelectRecipeFileAppFolder _selectrecipefile;
        Lynn_DPI_ATRepositoryFolders.KohyoungGUIAppFolder _kohyounggui;

        /// <summary>
        /// Gets the singleton class instance representing the Lynn_DPI_ATRepository element repository.
        /// </summary>
        [RepositoryFolder("0ee31be8-b7c0-4867-aed4-3f0533789467")]
        public static Lynn_DPI_ATRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Lynn_DPI_ATRepository() 
            : base("Lynn_DPI_ATRepository", "/", null, 0, false, "0ee31be8-b7c0-4867-aed4-3f0533789467", ".\\RepositoryImages\\Lynn_DPI_ATRepository0ee31be8.rximgres")
        {
            _cciloginwindow = new Lynn_DPI_ATRepositoryFolders.CCILoginWindowAppFolder(this);
            _ccimainwindow = new Lynn_DPI_ATRepositoryFolders.CCIMainWindowAppFolder(this);
            _inspectionregionsettings = new Lynn_DPI_ATRepositoryFolders.InspectionRegionSettingsAppFolder(this);
            _lynndpiat = new Lynn_DPI_ATRepositoryFolders.LynnDPIATAppFolder(this);
            _explorer = new Lynn_DPI_ATRepositoryFolders.ExplorerAppFolder(this);
            _selectrecipefile = new Lynn_DPI_ATRepositoryFolders.SelectRecipeFileAppFolder(this);
            _kohyounggui = new Lynn_DPI_ATRepositoryFolders.KohyoungGUIAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("0ee31be8-b7c0-4867-aed4-3f0533789467")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The CCILoginWindow folder.
        /// </summary>
        [RepositoryFolder("41fd3549-b30e-4b19-80d6-d11c3933f29d")]
        public virtual Lynn_DPI_ATRepositoryFolders.CCILoginWindowAppFolder CCILoginWindow
        {
            get { return _cciloginwindow; }
        }

        /// <summary>
        /// The CCIMainWindow folder.
        /// </summary>
        [RepositoryFolder("32658c71-369b-46b3-971a-ad23802facd5")]
        public virtual Lynn_DPI_ATRepositoryFolders.CCIMainWindowAppFolder CCIMainWindow
        {
            get { return _ccimainwindow; }
        }

        /// <summary>
        /// The InspectionRegionSettings folder.
        /// </summary>
        [RepositoryFolder("7b7cc356-6b4f-4429-ac48-e69a7067da19")]
        public virtual Lynn_DPI_ATRepositoryFolders.InspectionRegionSettingsAppFolder InspectionRegionSettings
        {
            get { return _inspectionregionsettings; }
        }

        /// <summary>
        /// The LynnDPIAT folder.
        /// </summary>
        [RepositoryFolder("892f40ad-7a90-4cdc-9e1a-47a48a83936e")]
        public virtual Lynn_DPI_ATRepositoryFolders.LynnDPIATAppFolder LynnDPIAT
        {
            get { return _lynndpiat; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("f112c047-9def-4ecb-b764-083e3f13e5e9")]
        public virtual Lynn_DPI_ATRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The SelectRecipeFile folder.
        /// </summary>
        [RepositoryFolder("e603f9b6-a8b1-4722-89a2-cfe80a1d5a95")]
        public virtual Lynn_DPI_ATRepositoryFolders.SelectRecipeFileAppFolder SelectRecipeFile
        {
            get { return _selectrecipefile; }
        }

        /// <summary>
        /// The KohyoungGUI folder.
        /// </summary>
        [RepositoryFolder("23424671-3a56-4425-84dc-73dc9dbe4a63")]
        public virtual Lynn_DPI_ATRepositoryFolders.KohyoungGUIAppFolder KohyoungGUI
        {
            get { return _kohyounggui; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Lynn_DPI_ATRepositoryFolders
    {
        /// <summary>
        /// The CCILoginWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("41fd3549-b30e-4b19-80d6-d11c3933f29d")]
        public partial class CCILoginWindowAppFolder : RepoGenBaseFolder
        {
            Lynn_DPI_ATRepositoryFolders.XIDPWLoginAreaFolder _xidpwloginarea;
            RepoItemInfo _loginInfo;

            /// <summary>
            /// Creates a new CCILoginWindow  folder.
            /// </summary>
            public CCILoginWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CCILoginWindow", "/form[@name='View']", parentFolder, 30000, null, false, "41fd3549-b30e-4b19-80d6-d11c3933f29d", "")
            {
                _xidpwloginarea = new Lynn_DPI_ATRepositoryFolders.XIDPWLoginAreaFolder(this);
                _loginInfo = new RepoItemInfo(this, "Login", "?/?/button[@automationid='xLoginButton']/text[@caption='Login']", "", 30000, null, "4397492c-fec2-4486-9f38-0b2d7409c6bc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("41fd3549-b30e-4b19-80d6-d11c3933f29d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("41fd3549-b30e-4b19-80d6-d11c3933f29d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Login item.
            /// </summary>
            [RepositoryItem("4397492c-fec2-4486-9f38-0b2d7409c6bc")]
            public virtual Ranorex.Text Login
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Login item info.
            /// </summary>
            [RepositoryItemInfo("4397492c-fec2-4486-9f38-0b2d7409c6bc")]
            public virtual RepoItemInfo LoginInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The XIDPWLoginArea folder.
            /// </summary>
            [RepositoryFolder("03d8af65-fa61-47a7-ade7-66dbfafe1633")]
            public virtual Lynn_DPI_ATRepositoryFolders.XIDPWLoginAreaFolder XIDPWLoginArea
            {
                get { return _xidpwloginarea; }
            }
        }

        /// <summary>
        /// The XIDPWLoginAreaFolder folder.
        /// </summary>
        [RepositoryFolder("03d8af65-fa61-47a7-ade7-66dbfafe1633")]
        public partial class XIDPWLoginAreaFolder : RepoGenBaseFolder
        {
            RepoItemInfo _sometextInfo;
            RepoItemInfo _textxpwInfo;
            RepoItemInfo _xpwwatermarkInfo;

            /// <summary>
            /// Creates a new XIDPWLoginArea  folder.
            /// </summary>
            public XIDPWLoginAreaFolder(RepoGenBaseFolder parentFolder) :
                    base("XIDPWLoginArea", "container[@automationid='xIDPWLoginArea']", parentFolder, 30000, null, false, "03d8af65-fa61-47a7-ade7-66dbfafe1633", "")
            {
                _sometextInfo = new RepoItemInfo(this, "SomeText", ".//text[@caption='']", "", 30000, null, "84b50f75-a4b0-45c0-bd1b-bb63922783f9");
                _textxpwInfo = new RepoItemInfo(this, "TextXPW", "?/?/text[@automationid='xPW']", "", 30000, null, "65c71dc5-1e74-4566-80b6-5f084db8a864");
                _xpwwatermarkInfo = new RepoItemInfo(this, "XPWWatermark", "?/?/text[@automationid='xPWWatermark']", "", 30000, null, "16ccf5f1-d9de-487d-b8f0-6513a4a8ee91");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("03d8af65-fa61-47a7-ade7-66dbfafe1633")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("03d8af65-fa61-47a7-ade7-66dbfafe1633")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeText item.
            /// </summary>
            [RepositoryItem("84b50f75-a4b0-45c0-bd1b-bb63922783f9")]
            public virtual Ranorex.Text SomeText
            {
                get
                {
                    return _sometextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SomeText item info.
            /// </summary>
            [RepositoryItemInfo("84b50f75-a4b0-45c0-bd1b-bb63922783f9")]
            public virtual RepoItemInfo SomeTextInfo
            {
                get
                {
                    return _sometextInfo;
                }
            }

            /// <summary>
            /// The TextXPW item.
            /// </summary>
            [RepositoryItem("65c71dc5-1e74-4566-80b6-5f084db8a864")]
            public virtual Ranorex.Text TextXPW
            {
                get
                {
                    return _textxpwInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextXPW item info.
            /// </summary>
            [RepositoryItemInfo("65c71dc5-1e74-4566-80b6-5f084db8a864")]
            public virtual RepoItemInfo TextXPWInfo
            {
                get
                {
                    return _textxpwInfo;
                }
            }

            /// <summary>
            /// The XPWWatermark item.
            /// </summary>
            [RepositoryItem("16ccf5f1-d9de-487d-b8f0-6513a4a8ee91")]
            public virtual Ranorex.Text XPWWatermark
            {
                get
                {
                    return _xpwwatermarkInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The XPWWatermark item info.
            /// </summary>
            [RepositoryItemInfo("16ccf5f1-d9de-487d-b8f0-6513a4a8ee91")]
            public virtual RepoItemInfo XPWWatermarkInfo
            {
                get
                {
                    return _xpwwatermarkInfo;
                }
            }
        }

        /// <summary>
        /// The CCIMainWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("32658c71-369b-46b3-971a-ad23802facd5")]
        public partial class CCIMainWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _createoropenrecipeInfo;
            RepoItemInfo _somebuttonInfo;
            RepoItemInfo _leftmenuopentooglebuttonInfo;
            RepoItemInfo _someindicatorInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _someindicator1Info;
            RepoItemInfo _sometextInfo;
            RepoItemInfo _menuopenrecipeInfo;

            /// <summary>
            /// Creates a new CCIMainWindow  folder.
            /// </summary>
            public CCIMainWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CCIMainWindow", "/form[@title='CCIMainWindow']", parentFolder, 30000, null, true, "32658c71-369b-46b3-971a-ad23802facd5", "")
            {
                _createoropenrecipeInfo = new RepoItemInfo(this, "CreateOrOpenRecipe", "container[@automationid='MainView']/?/?/text[@caption='Create or open recipe.']", "", 30000, null, "1ca25c88-a5ce-4306-aacd-c575283c4707");
                _somebuttonInfo = new RepoItemInfo(this, "SomeButton", "container[@automationid='WindowTitleBarPanel']/text/button[7]", "", 30000, null, "08c38375-1b37-4ad7-bdc9-8b2c5e396379");
                _leftmenuopentooglebuttonInfo = new RepoItemInfo(this, "LeftMenuOpenToogleButton", "container[@automationid='WindowTitleBarPanel']/?/?/button[@automationid='LeftMenuOpenToogleButton']", ".//button[@automationid='LeftMenuOpenToogleButton']", 30000, null, "61562d2a-c372-439a-89c4-7b1cc865cf35");
                _someindicatorInfo = new RepoItemInfo(this, "SomeIndicator", "indicator[1]", "indicator[1]", 30000, null, "9a218138-9e43-4ae1-9552-8a075e56667f");
                _textInfo = new RepoItemInfo(this, "Text", "container[@automationid='MainView']/?/?/table[@automationid='DevGrid']//cell[@automationid='PART_CellEditor']/checkbox[@automationid='tbxConnect']/text[@automationid='Text']", ".//text[@automationid='Text']", 30000, null, "1331a4f5-770d-435c-9543-0d016a69fe0e");
                _someindicator1Info = new RepoItemInfo(this, "SomeIndicator1", "indicator[2]", "indicator[2]", 30000, null, "bded332f-bdf3-40ec-9168-48857d170949");
                _sometextInfo = new RepoItemInfo(this, "SomeText", "container[@automationid='MainView']/?/?/container[@automationid='View']//text[@caption='Lynn_Array_BadMark']/text[@caption='']", ".//text[@caption='Lynn_Array_BadMark']/text[@caption='']", 30000, null, "d4b6b860-3698-49af-a31c-7a02f71e64d8");
                _menuopenrecipeInfo = new RepoItemInfo(this, "MenuOpenRecipe", "container[@automationid='MainView']/container[3]//button[@text='Open Recipe']/text[@automationid='HeaderTextBlock']", ".//text[@caption>'※ Some menus are disabled']/container[@caption='']/container[@caption='']/button[@text='Open Recipe']/text[@automationid='HeaderTextBlock']", 30000, null, "471fd4a3-6be2-453b-9509-13c55c285448");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("32658c71-369b-46b3-971a-ad23802facd5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("32658c71-369b-46b3-971a-ad23802facd5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CreateOrOpenRecipe item.
            /// </summary>
            [RepositoryItem("1ca25c88-a5ce-4306-aacd-c575283c4707")]
            public virtual Ranorex.Text CreateOrOpenRecipe
            {
                get
                {
                    return _createoropenrecipeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CreateOrOpenRecipe item info.
            /// </summary>
            [RepositoryItemInfo("1ca25c88-a5ce-4306-aacd-c575283c4707")]
            public virtual RepoItemInfo CreateOrOpenRecipeInfo
            {
                get
                {
                    return _createoropenrecipeInfo;
                }
            }

            /// <summary>
            /// The SomeButton item.
            /// </summary>
            [RepositoryItem("08c38375-1b37-4ad7-bdc9-8b2c5e396379")]
            public virtual Ranorex.Button SomeButton
            {
                get
                {
                    return _somebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SomeButton item info.
            /// </summary>
            [RepositoryItemInfo("08c38375-1b37-4ad7-bdc9-8b2c5e396379")]
            public virtual RepoItemInfo SomeButtonInfo
            {
                get
                {
                    return _somebuttonInfo;
                }
            }

            /// <summary>
            /// The LeftMenuOpenToogleButton item.
            /// </summary>
            [RepositoryItem("61562d2a-c372-439a-89c4-7b1cc865cf35")]
            public virtual Ranorex.Button LeftMenuOpenToogleButton
            {
                get
                {
                    return _leftmenuopentooglebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The LeftMenuOpenToogleButton item info.
            /// </summary>
            [RepositoryItemInfo("61562d2a-c372-439a-89c4-7b1cc865cf35")]
            public virtual RepoItemInfo LeftMenuOpenToogleButtonInfo
            {
                get
                {
                    return _leftmenuopentooglebuttonInfo;
                }
            }

            /// <summary>
            /// The SomeIndicator item.
            /// </summary>
            [RepositoryItem("9a218138-9e43-4ae1-9552-8a075e56667f")]
            public virtual Ranorex.Indicator SomeIndicator
            {
                get
                {
                    return _someindicatorInfo.CreateAdapter<Ranorex.Indicator>(true);
                }
            }

            /// <summary>
            /// The SomeIndicator item info.
            /// </summary>
            [RepositoryItemInfo("9a218138-9e43-4ae1-9552-8a075e56667f")]
            public virtual RepoItemInfo SomeIndicatorInfo
            {
                get
                {
                    return _someindicatorInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("1331a4f5-770d-435c-9543-0d016a69fe0e")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("1331a4f5-770d-435c-9543-0d016a69fe0e")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The SomeIndicator1 item.
            /// </summary>
            [RepositoryItem("bded332f-bdf3-40ec-9168-48857d170949")]
            public virtual Ranorex.Indicator SomeIndicator1
            {
                get
                {
                    return _someindicator1Info.CreateAdapter<Ranorex.Indicator>(true);
                }
            }

            /// <summary>
            /// The SomeIndicator1 item info.
            /// </summary>
            [RepositoryItemInfo("bded332f-bdf3-40ec-9168-48857d170949")]
            public virtual RepoItemInfo SomeIndicator1Info
            {
                get
                {
                    return _someindicator1Info;
                }
            }

            /// <summary>
            /// The SomeText item.
            /// </summary>
            [RepositoryItem("d4b6b860-3698-49af-a31c-7a02f71e64d8")]
            public virtual Ranorex.Text SomeText
            {
                get
                {
                    return _sometextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SomeText item info.
            /// </summary>
            [RepositoryItemInfo("d4b6b860-3698-49af-a31c-7a02f71e64d8")]
            public virtual RepoItemInfo SomeTextInfo
            {
                get
                {
                    return _sometextInfo;
                }
            }

            /// <summary>
            /// The MenuOpenRecipe item.
            /// </summary>
            [RepositoryItem("471fd4a3-6be2-453b-9509-13c55c285448")]
            public virtual Ranorex.Text MenuOpenRecipe
            {
                get
                {
                    return _menuopenrecipeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The MenuOpenRecipe item info.
            /// </summary>
            [RepositoryItemInfo("471fd4a3-6be2-453b-9509-13c55c285448")]
            public virtual RepoItemInfo MenuOpenRecipeInfo
            {
                get
                {
                    return _menuopenrecipeInfo;
                }
            }
        }

        /// <summary>
        /// The InspectionRegionSettingsAppFolder folder.
        /// </summary>
        [RepositoryFolder("7b7cc356-6b4f-4429-ac48-e69a7067da19")]
        public partial class InspectionRegionSettingsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btndualcloseInfo;

            /// <summary>
            /// Creates a new InspectionRegionSettings  folder.
            /// </summary>
            public InspectionRegionSettingsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("InspectionRegionSettings", "/form[@name='Popup']", parentFolder, 30000, null, true, "7b7cc356-6b4f-4429-ac48-e69a7067da19", "")
            {
                _btndualcloseInfo = new RepoItemInfo(this, "BtnDualClose", "?/?/button[@automationid='btnDualClose']", "", 30000, null, "5646b1ce-2367-4416-a41f-e82cc1e40e6e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7b7cc356-6b4f-4429-ac48-e69a7067da19")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7b7cc356-6b4f-4429-ac48-e69a7067da19")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnDualClose item.
            /// </summary>
            [RepositoryItem("5646b1ce-2367-4416-a41f-e82cc1e40e6e")]
            public virtual Ranorex.Button BtnDualClose
            {
                get
                {
                    return _btndualcloseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnDualClose item info.
            /// </summary>
            [RepositoryItemInfo("5646b1ce-2367-4416-a41f-e82cc1e40e6e")]
            public virtual RepoItemInfo BtnDualCloseInfo
            {
                get
                {
                    return _btndualcloseInfo;
                }
            }
        }

        /// <summary>
        /// The LynnDPIATAppFolder folder.
        /// </summary>
        [RepositoryFolder("892f40ad-7a90-4cdc-9e1a-47a48a83936e")]
        public partial class LynnDPIATAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _minimizeInfo;

            /// <summary>
            /// Creates a new LynnDPIAT  folder.
            /// </summary>
            public LynnDPIATAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LynnDPIAT", "/form[@title='Lynn_DPI_AT']", parentFolder, 30000, null, true, "892f40ad-7a90-4cdc-9e1a-47a48a83936e", "")
            {
                _minimizeInfo = new RepoItemInfo(this, "Minimize", "?/?/button[@accessiblename='Minimize']", "", 30000, null, "1dcd1d31-5d9d-422b-8261-51375f98a396");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("892f40ad-7a90-4cdc-9e1a-47a48a83936e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("892f40ad-7a90-4cdc-9e1a-47a48a83936e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Minimize item.
            /// </summary>
            [RepositoryItem("1dcd1d31-5d9d-422b-8261-51375f98a396")]
            public virtual Ranorex.Button Minimize
            {
                get
                {
                    return _minimizeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Minimize item info.
            /// </summary>
            [RepositoryItemInfo("1dcd1d31-5d9d-422b-8261-51375f98a396")]
            public virtual RepoItemInfo MinimizeInfo
            {
                get
                {
                    return _minimizeInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("f112c047-9def-4ecb-b764-083e3f13e5e9")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _neptunecallinoneInfo;
            RepoItemInfo _exportlynnInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/desktop[@processname='explorer']", parentFolder, 30000, null, true, "f112c047-9def-4ecb-b764-083e3f13e5e9", "")
            {
                _neptunecallinoneInfo = new RepoItemInfo(this, "NEPTUNECALLINONE", "?/?/list[@controlid='1']/listitem[@text='NEPTUNE_C_ALLINONE']", "", 30000, null, "5ae81f7d-46d8-4567-a7d7-4390f4ca4af1");
                _exportlynnInfo = new RepoItemInfo(this, "ExportLynn", "?/?/list[@controlid='1']/listitem[@text='Export_Lynn']", "", 30000, null, "bdf868c8-2a98-4abf-97cb-4bf03bc826e3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f112c047-9def-4ecb-b764-083e3f13e5e9")]
            public virtual Ranorex.Desktop Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Desktop>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f112c047-9def-4ecb-b764-083e3f13e5e9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NEPTUNECALLINONE item.
            /// </summary>
            [RepositoryItem("5ae81f7d-46d8-4567-a7d7-4390f4ca4af1")]
            public virtual Ranorex.ListItem NEPTUNECALLINONE
            {
                get
                {
                    return _neptunecallinoneInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The NEPTUNECALLINONE item info.
            /// </summary>
            [RepositoryItemInfo("5ae81f7d-46d8-4567-a7d7-4390f4ca4af1")]
            public virtual RepoItemInfo NEPTUNECALLINONEInfo
            {
                get
                {
                    return _neptunecallinoneInfo;
                }
            }

            /// <summary>
            /// The ExportLynn item.
            /// </summary>
            [RepositoryItem("bdf868c8-2a98-4abf-97cb-4bf03bc826e3")]
            public virtual Ranorex.ListItem ExportLynn
            {
                get
                {
                    return _exportlynnInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ExportLynn item info.
            /// </summary>
            [RepositoryItemInfo("bdf868c8-2a98-4abf-97cb-4bf03bc826e3")]
            public virtual RepoItemInfo ExportLynnInfo
            {
                get
                {
                    return _exportlynnInfo;
                }
            }
        }

        /// <summary>
        /// The SelectRecipeFileAppFolder folder.
        /// </summary>
        [RepositoryFolder("e603f9b6-a8b1-4722-89a2-cfe80a1d5a95")]
        public partial class SelectRecipeFileAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonopenInfo;
            RepoItemInfo _systemitemnamedisplayInfo;
            RepoItemInfo _text1148Info;

            /// <summary>
            /// Creates a new SelectRecipeFile  folder.
            /// </summary>
            public SelectRecipeFileAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SelectRecipeFile", "/form[@title='Select Recipe File']", parentFolder, 30000, null, true, "e603f9b6-a8b1-4722-89a2-cfe80a1d5a95", "")
            {
                _buttonopenInfo = new RepoItemInfo(this, "ButtonOpen", "button[@text='&Open']", "button[@text='&Open']", 30000, null, "829245ec-40d8-4f1c-9839-d7e703858b02");
                _systemitemnamedisplayInfo = new RepoItemInfo(this, "SystemItemNameDisplay", "element[@class='DUIViewWndClassName']//container[@caption='ShellView']/?/?/listitem[@automationid='2']/text[@automationid='System.ItemNameDisplay']", ".//listitem[@automationid='2']/text[@automationid='System.ItemNameDisplay']", 30000, null, "56977f94-f427-4225-94f5-476e9cca2afa");
                _text1148Info = new RepoItemInfo(this, "Text1148", "?/?/text[@controlid='1148']", "?/?/text[@controlid='1148']", 30000, null, "1dbcab17-d3f0-4a5a-88ea-668c4b0ef9fe");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e603f9b6-a8b1-4722-89a2-cfe80a1d5a95")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e603f9b6-a8b1-4722-89a2-cfe80a1d5a95")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOpen item.
            /// </summary>
            [RepositoryItem("829245ec-40d8-4f1c-9839-d7e703858b02")]
            public virtual Ranorex.Button ButtonOpen
            {
                get
                {
                    return _buttonopenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOpen item info.
            /// </summary>
            [RepositoryItemInfo("829245ec-40d8-4f1c-9839-d7e703858b02")]
            public virtual RepoItemInfo ButtonOpenInfo
            {
                get
                {
                    return _buttonopenInfo;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item.
            /// </summary>
            [RepositoryItem("56977f94-f427-4225-94f5-476e9cca2afa")]
            public virtual Ranorex.Text SystemItemNameDisplay
            {
                get
                {
                    return _systemitemnamedisplayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item info.
            /// </summary>
            [RepositoryItemInfo("56977f94-f427-4225-94f5-476e9cca2afa")]
            public virtual RepoItemInfo SystemItemNameDisplayInfo
            {
                get
                {
                    return _systemitemnamedisplayInfo;
                }
            }

            /// <summary>
            /// The Text1148 item.
            /// </summary>
            [RepositoryItem("1dbcab17-d3f0-4a5a-88ea-668c4b0ef9fe")]
            public virtual Ranorex.Text Text1148
            {
                get
                {
                    return _text1148Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1148 item info.
            /// </summary>
            [RepositoryItemInfo("1dbcab17-d3f0-4a5a-88ea-668c4b0ef9fe")]
            public virtual RepoItemInfo Text1148Info
            {
                get
                {
                    return _text1148Info;
                }
            }
        }

        /// <summary>
        /// The KohyoungGUIAppFolder folder.
        /// </summary>
        [RepositoryFolder("23424671-3a56-4425-84dc-73dc9dbe4a63")]
        public partial class KohyoungGUIAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lynnarraybadmarkkyjobInfo;

            /// <summary>
            /// Creates a new KohyoungGUI  folder.
            /// </summary>
            public KohyoungGUIAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KohyoungGUI", "/form[@title='']", parentFolder, 30000, null, true, "23424671-3a56-4425-84dc-73dc9dbe4a63", "")
            {
                _lynnarraybadmarkkyjobInfo = new RepoItemInfo(this, "LynnArrayBadMarkKyjob", "table[@class='SysListView32']/?/?/cell[@text='Lynn_Array_BadMark.kyjob']", ".//cell[@text='Lynn_Array_BadMark.kyjob']", 30000, null, "96e231d0-1bf3-46a9-95f3-4d9bbfff0396");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("23424671-3a56-4425-84dc-73dc9dbe4a63")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("23424671-3a56-4425-84dc-73dc9dbe4a63")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LynnArrayBadMarkKyjob item.
            /// </summary>
            [RepositoryItem("96e231d0-1bf3-46a9-95f3-4d9bbfff0396")]
            public virtual Ranorex.Cell LynnArrayBadMarkKyjob
            {
                get
                {
                    return _lynnarraybadmarkkyjobInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The LynnArrayBadMarkKyjob item info.
            /// </summary>
            [RepositoryItemInfo("96e231d0-1bf3-46a9-95f3-4d9bbfff0396")]
            public virtual RepoItemInfo LynnArrayBadMarkKyjobInfo
            {
                get
                {
                    return _lynnarraybadmarkkyjobInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
