///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Lynn_DPI_AT
{
    public partial class OpenFile_FromProduction
    {
        public const int FILE_DIALOG_TIMEOUT_MS = 15000;
        public const int APPLY_PRESETTING_TIMEOUT_MS = 15000;
        public const int TOP_VALIDATE_TIMEOUT_MS = 60000;
        public const int TOP_VALIDATE_POLL_MS = 2000;

        private void Init()
        {
            Report.Log(ReportLevel.Info, "OpenFile_FromProduction", "Module bat dau.");
            Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                string.Format("Enable = '{0}'", Enable));
            Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                string.Format("RecipeFilePath = '{0}'", RecipeFilePath));
            Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                string.Format("ModelName = '{0}'", ModelName));
            Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                string.Format("ProductionSetting = '{0}'", ProductionSetting));
            Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                string.Format("InspectionQuantity = '{0}'", InspectionQuantity));
            Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                string.Format("LotName = '{0}'", LotName));
        }

        public string OpenRecipeFileByPath()
        {
            if (!string.Equals(this.Enable, "Y", StringComparison.OrdinalIgnoreCase))
            {
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    string.Format("[SKIP] Enable='{0}' — bo qua row nay.", this.Enable));
                return this.RecipeFilePath;
            }

            string recipeFilePath = this.RecipeFilePath;

            if (string.IsNullOrEmpty(recipeFilePath))
                throw new ArgumentException("RecipeFilePath khong duoc de trong.");

            if (!File.Exists(recipeFilePath))
                throw new FileNotFoundException(
                    string.Format("File khong ton tai: '{0}'", recipeFilePath), recipeFilePath);

            Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                string.Format("Target file: '{0}'", recipeFilePath));

            try
            {
                // --- Buoc 1: Click BtnOpenFileFromProduction ---
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    "Buoc 1: Click BtnOpenFileFromProduction...");
                repo.CCIMainWindow.Area1.BtnOpenFileFromProduction.Click();
                Delay.Milliseconds(500);

                // --- Buoc 2: Cho dialog xuat hien ---
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    "Buoc 2: Cho dialog Select Recipe File...");
                if (!repo.SelectRecipeFile.SelfInfo.Exists(FILE_DIALOG_TIMEOUT_MS))
                {
                    Report.Screenshot(repo.CCIMainWindow.Self, true);
                    throw new Exception(
                        "Select Recipe File dialog khong xuat hien sau khi click BtnOpenFileFromProduction.");
                }
                Report.Log(ReportLevel.Success, "OpenFile_FromProduction",
                    "Buoc 2 OK: dialog xuat hien.");

                // --- Buoc 3: Nhap path ---
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction", "Buoc 3: Nhap path...");
                EnterPathIntoFileNameField(recipeFilePath);

                // --- Buoc 4: Click Open ---
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction", "Buoc 4: Click Open...");
                repo.BtnOpenInDialog.Click();
                Delay.Milliseconds(1000);

                // --- Buoc 5: Cho Production Presetting dialog xuat hien ---
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    "Buoc 5: Cho Production Presetting dialog...");
                if (!repo.InspectionRegionSettings.SelfInfo.Exists(APPLY_PRESETTING_TIMEOUT_MS))
                {
                    Report.Screenshot(repo.CCIMainWindow.Self, true);
                    throw new Exception(string.Format(
                        "Production Presetting dialog khong xuat hien sau {0}ms.", APPLY_PRESETTING_TIMEOUT_MS));
                }
                Report.Log(ReportLevel.Success, "OpenFile_FromProduction",
                    "Buoc 5 OK: Production Presetting dialog da xuat hien.");

                // --- Buoc 5.5: Chon Production Setting theo test data ---
                SelectProductionSetting();

                // --- Buoc 6: Click Apply voi fallback ---
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    "Buoc 6: Click Apply voi fallback...");
                ClickApplyWithFallback();

                // --- Buoc 7: Cho app load sau Apply ---
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    "Buoc 7: Cho app load sau Apply...");
                Delay.Milliseconds(2000);

                // --- Buoc 8: Validate TopTextRecipeName chua ModelName ---
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    "Buoc 8: Validate ModelName tai vung TOP...");
                ValidateTopModelName();
            }
            finally
            {
                CleanupDialog();
            }

            return this.RecipeFilePath;
        }

        private void EnterPathIntoFileNameField(string path)
        {
            repo.SelectRecipeFile.Self.Activate();
            Delay.Milliseconds(300);
            repo.SelectRecipeFile.Text1148.Click();
            Delay.Milliseconds(300);

            Report.Log(ReportLevel.Info, "OpenFile_FromProduction", "Set TextValue...");
            repo.SelectRecipeFile.Text1148.TextValue = path;
            Delay.Milliseconds(500);

            string fieldText = ReadFileNameField();
            Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                string.Format("Field text: '{0}'", fieldText));

            bool match = !string.IsNullOrEmpty(fieldText)
                && (fieldText.Equals(path, StringComparison.OrdinalIgnoreCase)
                    || path.EndsWith(fieldText, StringComparison.OrdinalIgnoreCase));

            if (!match)
                throw new Exception(string.Format(
                    "Khong the set path. Actual: '{0}', Expected: '{1}'", fieldText, path));

            Report.Log(ReportLevel.Success, "OpenFile_FromProduction",
                string.Format("Path set dung: '{0}'", fieldText));
        }

        private string ReadFileNameField()
        {
            try { return repo.SelectRecipeFile.Text1148.TextValue; }
            catch
            {
                try { return repo.SelectRecipeFile.Text1148.Element.GetAttributeValueText("WindowText"); }
                catch { return "(khong doc duoc)"; }
            }
        }

        private void ValidateTopModelName()
        {
            string expected = this.ModelName;

            if (string.IsNullOrEmpty(expected))
            {
                Report.Log(ReportLevel.Error, "OpenFile_FromProduction",
                    "ModelName is empty. Check ModeName -> ModelName binding in Ranorex Studio.");
                throw new Exception(
                    "ModelName is empty. Check ModeName -> ModelName binding in Ranorex Studio.");
            }

            Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                string.Format("Expected ModelName = '{0}'", expected));

            var sw = System.Diagnostics.Stopwatch.StartNew();
            string actualText = null;

            while (sw.ElapsedMilliseconds < TOP_VALIDATE_TIMEOUT_MS)
            {
                try
                {
                    if (repo.CCIMainWindow.Area1.TopTextRecipeNameInfo.Exists(0))
                    {
                        var el = repo.CCIMainWindow.Area1.TopTextRecipeName.Element;

                        actualText = el.GetAttributeValueText("Text");
                        if (string.IsNullOrEmpty(actualText))
                            actualText = el.GetAttributeValueText("SelectionText");

                        Report.Log(ReportLevel.Debug, "OpenFile_FromProduction",
                            string.Format("ValidateTop poll: Text='{0}' ({1}ms)",
                                actualText ?? "(null)", sw.ElapsedMilliseconds));

                        if (!string.IsNullOrEmpty(actualText) && actualText.Contains(expected))
                        {
                            sw.Stop();
                            Report.Log(ReportLevel.Success, "OpenFile_FromProduction",
                                string.Format("TOP ModelName matched: '{0}' contains '{1}' ({2}ms)",
                                    actualText, expected, sw.ElapsedMilliseconds));
                            return;
                        }
                    }
                }
                catch (Exception ex)
                {
                    Report.Log(ReportLevel.Debug, "OpenFile_FromProduction",
                        string.Format("ValidateTop poll exception: {0}", ex.Message));
                }

                Delay.Milliseconds(TOP_VALIDATE_POLL_MS);
            }

            sw.Stop();
            Report.Screenshot(repo.CCIMainWindow.Self, true);
            Report.Log(ReportLevel.Error, "OpenFile_FromProduction",
                string.Format("TOP ModelName FAIL. Expected contains: '{0}', Actual Text: '{1}' ({2}ms)",
                    expected, actualText ?? "(null)", sw.ElapsedMilliseconds));
            throw new Exception(string.Format(
                "ValidateTopModelName FAIL: TopTextRecipeName Text = '{0}', expected contains '{1}'",
                actualText ?? "(null)", expected));
        }

        private void SelectProductionSetting()
        {
            string setting = (this.ProductionSetting ?? "").Trim();

            if (string.IsNullOrEmpty(setting))
            {
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    "ProductionSetting rong — giu nguyen setting mac dinh.");
                return;
            }

            Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                string.Format("Buoc 5.5: Chon ProductionSetting = '{0}'", setting));

            switch (setting.ToLowerInvariant())
            {
                case "notuse":
                    ClickRadioAndVerify(
                        repo.InspectionRegionSettings.RadioNotUse,
                        "RadioNotUse");
                    break;

                case "quantity":
                    ClickRadioAndVerify(
                        repo.InspectionRegionSettings.RadioQuantityInspection,
                        "RadioQuantityInspection");

                    string qty = (this.InspectionQuantity ?? "").Trim();
                    if (string.IsNullOrEmpty(qty))
                        throw new ArgumentException(
                            "ProductionSetting=Quantity nhung InspectionQuantity rong.");

                    int qtyNum;
                    if (!int.TryParse(qty, out qtyNum) || qtyNum <= 0)
                        throw new ArgumentException(string.Format(
                            "InspectionQuantity = '{0}' khong hop le. Can so nguyen duong.", qty));

                    Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                        string.Format("Nhap InspectionQuantity = '{0}'...", qty));
                    Keyboard.Press("{Tab}");
                    Delay.Milliseconds(300);
                    Keyboard.Press(qty);
                    Report.Log(ReportLevel.Success, "OpenFile_FromProduction",
                        string.Format("Da nhap InspectionQuantity = '{0}'.", qty));
                    break;

                case "lotproduction":
                    ClickRadioAndVerify(
                        repo.InspectionRegionSettings.RadioLotProduction,
                        "RadioLotProduction");
                    HandleLotProductionSettings();
                    break;

                default:
                    Report.Log(ReportLevel.Warn, "OpenFile_FromProduction",
                        string.Format("ProductionSetting = '{0}' khong nhan dien. Giu nguyen.", setting));
                    break;
            }
        }

        private const int LOT_DIALOG_TIMEOUT_MS = 15000;
        private const int LOT_DIALOG_POLL_MS = 500;
        private const string LOT_DIALOG_RXPATH = "/form[@processname='KohyoungGUI']//text[@automationid='lotIDTextBox']";

        private bool TryFindLotDialog(int timeoutMs)
        {
            Ranorex.Text element;
            return Host.Local.TryFindSingle(LOT_DIALOG_RXPATH, timeoutMs, out element);
        }

        private void HandleLotProductionSettings()
        {
            string lotName = (this.LotName ?? "").Trim();

            if (string.IsNullOrEmpty(lotName))
            {
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    "LotName rong — skip LOT Settings, giu nguyen.");
                return;
            }

            Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                "Click BtnLotSettings de mo LOT Settings...");
            repo.InspectionRegionSettings.BtnLotSettings.Click();
            Delay.Milliseconds(500);

            if (!TryFindLotDialog(LOT_DIALOG_TIMEOUT_MS))
            {
                Report.Screenshot(repo.CCIMainWindow.Self, true);
                throw new Exception(string.Format(
                    "LOT Settings dialog khong xuat hien sau {0}ms.", LOT_DIALOG_TIMEOUT_MS));
            }
            Report.Log(ReportLevel.Success, "OpenFile_FromProduction",
                "LOT Settings dialog da mo.");

            Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                string.Format("Nhap LOT ID = '{0}'...", lotName));
            repo.KohyoungGUI1.TxtLotID.Click();
            Delay.Milliseconds(200);
            Keyboard.Press("{Home}");
            Delay.Milliseconds(100);
            Keyboard.Press("{Shift down}{End}{Shift up}");
            Delay.Milliseconds(100);
            Keyboard.Press("{Delete}");
            Delay.Milliseconds(200);
            Keyboard.Press(lotName);
            Report.Log(ReportLevel.Success, "OpenFile_FromProduction",
                string.Format("Da nhap LOT ID = '{0}'.", lotName));

            string qty = (this.InspectionQuantity ?? "").Trim();
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(200);

            if (!string.IsNullOrEmpty(qty))
            {
                int qtyNum;
                if (!int.TryParse(qty, out qtyNum) || qtyNum <= 0)
                    throw new ArgumentException(string.Format(
                        "InspectionQuantity = '{0}' khong hop le. Can so nguyen duong.", qty));

                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    string.Format("Nhap Planned Qty = '{0}'...", qty));
                Keyboard.Press("{Home}");
                Delay.Milliseconds(100);
                Keyboard.Press("{Shift down}{End}{Shift up}");
                Delay.Milliseconds(100);
                Keyboard.Press("{Delete}");
                Delay.Milliseconds(200);
                Keyboard.Press(qty);
                Report.Log(ReportLevel.Success, "OpenFile_FromProduction",
                    string.Format("Da nhap Planned Qty = '{0}'.", qty));
            }
            else
            {
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    "InspectionQuantity rong — giu nguyen Planned Qty mac dinh.");
            }

            Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                "Click BtnLotApply...");
            repo.KohyoungGUI1.BtnLotApply.Click();
            Delay.Milliseconds(1000);

            if (!TryFindLotDialog(LOT_DIALOG_POLL_MS))
            {
                Report.Log(ReportLevel.Success, "OpenFile_FromProduction",
                    "LOT Settings da dong sau Apply.");
                return;
            }

            var sw = System.Diagnostics.Stopwatch.StartNew();
            while (sw.ElapsedMilliseconds < LOT_DIALOG_TIMEOUT_MS)
            {
                if (!TryFindLotDialog(LOT_DIALOG_POLL_MS))
                {
                    sw.Stop();
                    Report.Log(ReportLevel.Success, "OpenFile_FromProduction",
                        string.Format("LOT Settings da dong ({0}ms).", sw.ElapsedMilliseconds));
                    return;
                }
            }

            sw.Stop();
            Report.Screenshot(repo.CCIMainWindow.Self, true);
            Report.Log(ReportLevel.Error, "OpenFile_FromProduction",
                string.Format("LOT Settings KHONG dong sau {0}ms. "
                    + "Co the LOT ID = '{1}' da ton tai (loi 'already exists') "
                    + "hoac loi khac. Xem screenshot.", LOT_DIALOG_TIMEOUT_MS, lotName));
            throw new Exception(string.Format(
                "LOT Settings dialog khong dong sau {0}ms. LOT ID = '{1}' co the da ton tai.",
                LOT_DIALOG_TIMEOUT_MS, lotName));
        }

        private void ClickRadioAndVerify(RadioButton radio, string radioName)
        {
            const int VERIFY_TIMEOUT_MS = 3000;
            const int VERIFY_POLL_MS = 500;

            radio.EnsureVisible();

            if (!radio.Element.Enabled)
            {
                Report.Screenshot(repo.InspectionRegionSettings.Self, true);
                throw new Exception(string.Format(
                    "{0} disabled — dialog co the dang loading.", radioName));
            }

            Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                string.Format("Click {0}...", radioName));
            radio.Click();

            var sw = System.Diagnostics.Stopwatch.StartNew();
            while (sw.ElapsedMilliseconds < VERIFY_TIMEOUT_MS)
            {
                if (radio.Checked)
                {
                    sw.Stop();
                    Report.Log(ReportLevel.Success, "OpenFile_FromProduction",
                        string.Format("{0} da duoc chon ({1}ms).", radioName, sw.ElapsedMilliseconds));
                    return;
                }
                Delay.Milliseconds(VERIFY_POLL_MS);
            }

            sw.Stop();
            Report.Screenshot(repo.InspectionRegionSettings.Self, true);
            throw new Exception(string.Format(
                "{0} khong duoc chon sau khi click ({1}ms).", radioName, VERIFY_TIMEOUT_MS));
        }

        private void ClickApplyWithFallback()
        {
            const int DIALOG_LOADING_TIMEOUT_MS = 60000;
            const int DIALOG_POLL_MS = 2000;
            const int DIALOG_LOG_INTERVAL_MS = 10000;

            // Strategy 1: Native WPF Apply — Adapter.Click
            try
            {
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    "Strategy 1: Native WPF Apply.Click()...");
                repo.InspectionRegionSettings.BtnApplyProductionPresetting.Click();
                Delay.Milliseconds(500);
                if (WaitForDialogClose("Strategy 1 — Native WPF", DIALOG_LOADING_TIMEOUT_MS, DIALOG_POLL_MS, DIALOG_LOG_INTERVAL_MS))
                    return;
            }
            catch (Exception ex)
            {
                Report.Log(ReportLevel.Warn, "OpenFile_FromProduction",
                    string.Format("Strategy 1 exception: {0}", ex.Message));
            }

            // Strategy 2: Native WPF Apply — Focus + Space
            try
            {
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    "Strategy 2: Focus + Space...");
                repo.InspectionRegionSettings.BtnApplyProductionPresetting.Focus();
                Delay.Milliseconds(200);
                Keyboard.Press("{Space}");
                Delay.Milliseconds(500);
                if (WaitForDialogClose("Strategy 2 — Focus+Space", DIALOG_LOADING_TIMEOUT_MS, DIALOG_POLL_MS, DIALOG_LOG_INTERVAL_MS))
                    return;
            }
            catch (Exception ex)
            {
                Report.Log(ReportLevel.Warn, "OpenFile_FromProduction",
                    string.Format("Strategy 2 exception: {0}", ex.Message));
            }

            // Strategy 3: UIA BtnApplyProductionPresetting — Click
            try
            {
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    "Strategy 3: UIA BtnApplyProductionPresetting.Click()...");
                if (repo.InspectionRegionSettings.BtnApplyProductionPresettingInfo.Exists(2000))
                {
                    repo.InspectionRegionSettings.BtnApplyProductionPresetting.Click();
                    Delay.Milliseconds(500);
                    if (WaitForDialogClose("Strategy 3 — UIA", DIALOG_LOADING_TIMEOUT_MS, DIALOG_POLL_MS, DIALOG_LOG_INTERVAL_MS))
                        return;
                }
                else
                {
                    Report.Log(ReportLevel.Warn, "OpenFile_FromProduction",
                        "Strategy 3: BtnApplyProductionPresetting khong tim thay.");
                }
            }
            catch (Exception ex)
            {
                Report.Log(ReportLevel.Warn, "OpenFile_FromProduction",
                    string.Format("Strategy 3 exception: {0}", ex.Message));
            }

            // Strategy 4: Native WPF Apply — Coordinate click via ScreenRectangle
            try
            {
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    "Strategy 4: Coordinate click via ScreenRectangle...");
                var rect = repo.InspectionRegionSettings.BtnApplyProductionPresetting.Element.ScreenRectangle;
                int cx = rect.Location.X + rect.Width / 2;
                int cy = rect.Location.Y + rect.Height / 2;
                Mouse.MoveTo(new Point(cx, cy));
                Mouse.Click();
                Delay.Milliseconds(500);
                if (WaitForDialogClose("Strategy 4 — Coordinate", DIALOG_LOADING_TIMEOUT_MS, DIALOG_POLL_MS, DIALOG_LOG_INTERVAL_MS))
                    return;
            }
            catch (Exception ex)
            {
                Report.Log(ReportLevel.Warn, "OpenFile_FromProduction",
                    string.Format("Strategy 4 exception: {0}", ex.Message));
            }

            Report.Screenshot(repo.CCIMainWindow.Self, true);
            throw new Exception("Tat ca 4 strategy click Apply deu that bai. Dialog van con mo.");
        }

        private bool WaitForDialogClose(string strategyName, int timeoutMs, int pollMs, int logIntervalMs)
        {
            var sw = System.Diagnostics.Stopwatch.StartNew();
            long lastLogMs = 0;

            while (sw.ElapsedMilliseconds < timeoutMs)
            {
                if (!repo.InspectionRegionSettings.SelfInfo.Exists(pollMs))
                {
                    sw.Stop();
                    Report.Log(ReportLevel.Success, "OpenFile_FromProduction",
                        string.Format("Buoc 6 OK: Apply clicked ({0}). Dialog dong sau {1}ms.",
                            strategyName, sw.ElapsedMilliseconds));
                    return true;
                }

                long elapsed = sw.ElapsedMilliseconds;
                if (elapsed - lastLogMs >= logIntervalMs)
                {
                    lastLogMs = elapsed;
                    Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                        string.Format("{0}: dialog van mo, dang cho app load... ({1}/{2}s)",
                            strategyName, elapsed / 1000, timeoutMs / 1000));
                }
            }

            sw.Stop();
            Report.Log(ReportLevel.Warn, "OpenFile_FromProduction",
                string.Format("{0}: dialog van con mo sau {1}ms.", strategyName, timeoutMs));
            return false;
        }

        private void CleanupDialog()
        {
            try
            {
                if (repo.InspectionRegionSettings.SelfInfo.Exists(1000))
                {
                    Report.Log(ReportLevel.Warn, "OpenFile_FromProduction",
                        "CleanupDialog: Production Presetting con mo — dang dong...");
                    Keyboard.Press("{Escape}");
                    Delay.Milliseconds(500);
                    if (repo.InspectionRegionSettings.SelfInfo.Exists(1000))
                        repo.InspectionRegionSettings.Self.Close();
                }
            }
            catch (Exception ex)
            {
                Report.Log(ReportLevel.Warn, "OpenFile_FromProduction",
                    string.Format("CleanupDialog InspectionRegionSettings exception (non-fatal): {0}", ex.Message));
            }

            try
            {
                if (repo.SelectRecipeFile.SelfInfo.Exists(1000))
                {
                    Report.Log(ReportLevel.Warn, "OpenFile_FromProduction",
                        "CleanupDialog: SelectRecipeFile con mo — dang dong...");
                    Keyboard.Press("{Escape}");
                    Delay.Milliseconds(500);
                    if (repo.SelectRecipeFile.SelfInfo.Exists(1000))
                        repo.SelectRecipeFile.Self.Close();
                }
            }
            catch (Exception ex)
            {
                Report.Log(ReportLevel.Warn, "OpenFile_FromProduction",
                    string.Format("CleanupDialog SelectRecipeFile exception (non-fatal): {0}", ex.Message));
            }
        }

    }
}
