///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Lynn_DPI_AT
{
    public partial class OpenFile
    {
        public const int FILE_DIALOG_TIMEOUT_MS = 15000;
        public const int DIALOG_CLOSE_TIMEOUT_MS = 5000;
        public const int MENU_OPEN_RECIPE_TIMEOUT_MS = 50000;
        public const int MENU_POLL_INTERVAL_MS = 400;

        private void Init()
        {
            Report.Log(ReportLevel.Info, "OpenFile", "OpenFile bat dau.");
            Report.Log(ReportLevel.Info, "OpenFile",
                string.Format("RecipeFilePath = '{0}'", RecipeFilePath));
            Report.Log(ReportLevel.Info, "OpenFile",
                string.Format("ExpectedFileName = '{0}'", ExpectedFileName));
        }

        public void OpenRecipeFileByPath(string recipeFilePath)
        {
            if (string.IsNullOrEmpty(recipeFilePath))
                throw new ArgumentException("recipeFilePath khong duoc de trong.", "recipeFilePath");

            if (!System.IO.File.Exists(recipeFilePath))
                throw new System.IO.FileNotFoundException(
                    string.Format("File khong ton tai tren disk: '{0}'", recipeFilePath), recipeFilePath);

            Report.Log(ReportLevel.Info, "OpenFile",
                string.Format("Target file: '{0}'", recipeFilePath));

            // --- Buoc 1: Verify CCIMainWindow ---
            Report.Log(ReportLevel.Info, "OpenFile", "Buoc 1: Kiem tra CCIMainWindow...");
            if (!repo.CCIMainWindow.SelfInfo.Exists(10000))
                throw new Exception("CCIMainWindow khong ton tai sau 10s.");
            Report.Log(ReportLevel.Success, "OpenFile", "Buoc 1 OK.");

            // --- Buoc 2: Activate ---
            Report.Log(ReportLevel.Info, "OpenFile", "Buoc 2: Activate CCIMainWindow...");
            repo.CCIMainWindow.Self.Activate();
            Delay.Milliseconds(500);
            Report.Log(ReportLevel.Success, "OpenFile", "Buoc 2 OK.");

            // --- Buoc 3: Menu click ---
            Report.Log(ReportLevel.Info, "OpenFile", "Buoc 3: Click LeftMenuOpenToogleButton...");
            repo.CCIMainWindow.LeftMenuOpenToogleButton.Click();
            Delay.Milliseconds(300);

            Report.Log(ReportLevel.Info, "OpenFile", "Buoc 3: Cho MenuOpenRecipe san sang (max 50s)...");
            bool menuReady = WaitForMenuOpenRecipeClickable(MENU_OPEN_RECIPE_TIMEOUT_MS, MENU_POLL_INTERVAL_MS);
            if (!menuReady)
            {
                Report.Screenshot(repo.CCIMainWindow.Self, true);
                Report.Log(ReportLevel.Error, "OpenFile",
                    string.Format("Buoc 3 THAT BAI: MenuOpenRecipe khong visible/clickable sau {0}s.", MENU_OPEN_RECIPE_TIMEOUT_MS / 1000));
                throw new Exception(string.Format(
                    "MenuOpenRecipe khong san sang sau {0}s. Menu sidebar co the chua mo hoac element khong visible.", MENU_OPEN_RECIPE_TIMEOUT_MS / 1000));
            }

            Report.Log(ReportLevel.Info, "OpenFile", "Buoc 3: Click MenuOpenRecipe...");
            repo.CCIMainWindow.MenuOpenRecipe.Click();
            Delay.Milliseconds(500);

            if (!repo.SelectRecipeFile.SelfInfo.Exists(FILE_DIALOG_TIMEOUT_MS))
            {
                Report.Screenshot(repo.CCIMainWindow.Self, true);
                Report.Log(ReportLevel.Error, "OpenFile", "Buoc 3 THAT BAI: dialog khong xuat hien sau khi click MenuOpenRecipe.");
                throw new Exception("Select Recipe File dialog khong xuat hien sau khi click MenuOpenRecipe.");
            }
            Report.Log(ReportLevel.Success, "OpenFile", "Buoc 3 OK: dialog xuat hien.");

            // --- Buoc 4: Nhap path vao File name ---
            Report.Log(ReportLevel.Info, "OpenFile", "Buoc 4: Nhap path...");
            EnterPathIntoFileNameField(recipeFilePath);

            // --- Buoc 5: Click Open ---
            Report.Log(ReportLevel.Info, "OpenFile", "Buoc 5: Click Open...");
            repo.ButtonOpen.Click();
            Delay.Milliseconds(1000);

            // --- Buoc 6: Cho app load (tam thoi khong verify dialog — tranh fail ao) ---
            Report.Log(ReportLevel.Info, "OpenFile", "Buoc 6: Da click Open. Cho app load...");
            Delay.Milliseconds(2000);
            Report.Log(ReportLevel.Info, "OpenFile",
                string.Format("Buoc 6 INFO: Click Open hoan tat. File target: '{0}'", recipeFilePath));

            // --- Buoc 7: Investigation (PHASE 1 — tam thoi) ---
            Report.Log(ReportLevel.Info, "OpenFile", "Buoc 7: Cho SomeText xuat hien de investigate...");
            bool someTextAppeared = repo.CCIMainWindow.SomeTextInfo.Exists(30000);
            Report.Log(ReportLevel.Info, "OpenFile",
                string.Format("Buoc 7: SomeText.Exists(30s) = {0}", someTextAppeared));
            InvestigateModelNameElement();
        }

        private void EnterPathIntoFileNameField(string path)
        {
            repo.SelectRecipeFile.Self.Activate();
            Delay.Milliseconds(300);
            repo.SelectRecipeFile.Text1148.Click();
            Delay.Milliseconds(300);

            Report.Log(ReportLevel.Info, "OpenFile", "Thu set TextValue truc tiep...");
            repo.SelectRecipeFile.Text1148.TextValue = path;
            Delay.Milliseconds(500);

            string fieldText = ReadFileNameField();
            Report.Log(ReportLevel.Info, "OpenFile",
                string.Format("Field text sau set TextValue: '{0}'", fieldText));

            bool match = !string.IsNullOrEmpty(fieldText)
                && (fieldText.Equals(path, StringComparison.OrdinalIgnoreCase)
                    || path.EndsWith(fieldText, StringComparison.OrdinalIgnoreCase));

            if (!match)
            {
                Report.Log(ReportLevel.Error, "OpenFile",
                    string.Format("THAT BAI: field = '{0}', expected = '{1}'", fieldText, path));
                throw new Exception(string.Format(
                    "Khong the set path vao File name field. Actual: '{0}', Expected: '{1}'",
                    fieldText, path));
            }
            Report.Log(ReportLevel.Success, "OpenFile",
                string.Format("Path set dung: '{0}'", fieldText));
        }

        private string ReadFileNameField()
        {
            try
            {
                return repo.SelectRecipeFile.Text1148.TextValue;
            }
            catch
            {
                try
                {
                    return repo.SelectRecipeFile.Text1148.Element.GetAttributeValueText("WindowText");
                }
                catch
                {
                    return "(khong doc duoc)";
                }
            }
        }

        private bool WaitForMenuOpenRecipeClickable(int timeoutMs, int pollIntervalMs)
        {
            var stopwatch = System.Diagnostics.Stopwatch.StartNew();
            int attempt = 0;

            while (stopwatch.ElapsedMilliseconds < timeoutMs)
            {
                attempt++;
                try
                {
                    if (repo.CCIMainWindow.MenuOpenRecipeInfo.Exists(0))
                    {
                        var element = repo.CCIMainWindow.MenuOpenRecipe;
                        bool visible = element.Visible;
                        bool enabled = element.Enabled;

                        Report.Log(ReportLevel.Debug, "OpenFile",
                            string.Format("Poll #{0} ({1}ms): Exists=True, Visible={2}, Enabled={3}",
                                attempt, stopwatch.ElapsedMilliseconds, visible, enabled));

                        if (visible && enabled)
                        {
                            element.EnsureVisible();
                            Delay.Milliseconds(200);
                            Report.Log(ReportLevel.Info, "OpenFile",
                                string.Format("MenuOpenRecipe san sang sau {0}ms (poll #{1}).",
                                    stopwatch.ElapsedMilliseconds, attempt));
                            return true;
                        }
                    }
                    else
                    {
                        if (attempt <= 3 || attempt % 10 == 0)
                            Report.Log(ReportLevel.Debug, "OpenFile",
                                string.Format("Poll #{0} ({1}ms): MenuOpenRecipe chua Exists.",
                                    attempt, stopwatch.ElapsedMilliseconds));
                    }
                }
                catch (Exception ex)
                {
                    Report.Log(ReportLevel.Debug, "OpenFile",
                        string.Format("Poll #{0} ({1}ms): Exception — {2}",
                            attempt, stopwatch.ElapsedMilliseconds, ex.Message));
                }

                Delay.Milliseconds(pollIntervalMs);
            }

            Report.Log(ReportLevel.Error, "OpenFile",
                string.Format("MenuOpenRecipe KHONG san sang sau {0}ms ({1} polls).",
                    stopwatch.ElapsedMilliseconds, attempt));
            return false;
        }

        private void Finish()
        {
            if (repo.SelectRecipeFile.SelfInfo.Exists(1000))
            {
                Report.Log(ReportLevel.Warn, "OpenFile", "Finish: dialog con mo — dang dong...");
                Keyboard.Press("{Escape}");
                Delay.Milliseconds(500);
                if (repo.SelectRecipeFile.SelfInfo.Exists(1000))
                    repo.SelectRecipeFile.Self.Close();
            }
        }

        // =====================================================================
        // PHASE 1 INVESTIGATION — temporary, will be removed after investigation
        // =====================================================================
        private static readonly string[] PROBE_ATTRS = {
            "Caption", "Text", "WindowText",
            "AccessibleName", "AccessibleValue",
            "Name", "Value",
            "AutomationId", "ClassName", "ControlType",
            "TagName", "InnerText", "OuterText"
        };

        private void InvestigateModelNameElement()
        {
            Report.Log(ReportLevel.Info, "OpenFile",
                "=== INVESTIGATE MODEL NAME ELEMENT START ===");
            Report.Log(ReportLevel.Info, "OpenFile",
                string.Format("Expected ModelName (CSV/default) = '{0}'", this.ModelName));

            try
            {
                // --- SomeText exists check ---
                bool exists = repo.CCIMainWindow.SomeTextInfo.Exists(5000);
                Report.Log(ReportLevel.Info, "OpenFile",
                    string.Format("[PROBE] SomeText.Exists(5s) = {0}", exists));
                if (!exists)
                {
                    Report.Log(ReportLevel.Warn, "OpenFile",
                        "[PROBE] SomeText khong ton tai — chi log START/END, khong co du lieu.");
                }
                else
                {
                    var child = repo.CCIMainWindow.SomeText.Element;
                    LogElement(child, "SomeText(CHILD)");

                    // --- Traverse UP 4 levels ---
                    var cur = child.Parent;
                    for (int level = 1; level <= 4 && cur != null; level++)
                    {
                        LogElement(cur, string.Format("ANCESTOR_L{0}", level));
                        LogChildren(cur, string.Format("ANCESTOR_L{0}", level));
                        cur = cur.Parent;
                    }
                }
            }
            catch (Exception ex)
            {
                Report.Log(ReportLevel.Error, "OpenFile",
                    string.Format("[PROBE] Exception: {0}", ex.Message));
            }

            Report.Log(ReportLevel.Info, "OpenFile",
                "=== INVESTIGATE MODEL NAME ELEMENT END ===");
        }

        private void LogElement(Ranorex.Core.Element el, string label)
        {
            if (el == null)
            {
                Report.Log(ReportLevel.Info, "OpenFile",
                    string.Format("[{0}] element = null", label));
                return;
            }

            foreach (string attr in PROBE_ATTRS)
            {
                try
                {
                    string val = el.GetAttributeValueText(attr);
                    if (val == null)
                        Report.Log(ReportLevel.Info, "OpenFile",
                            string.Format("[{0}] {1} = (null)", label, attr));
                    else
                        Report.Log(ReportLevel.Info, "OpenFile",
                            string.Format("[{0}] {1} = '{2}'", label, attr, val));
                }
                catch
                {
                    // attribute khong ton tai tren element nay — bo qua
                }
            }
        }

        private void LogChildren(Ranorex.Core.Element parent, string parentLabel)
        {
            try
            {
                var children = parent.Children;
                if (children == null || children.Count == 0)
                {
                    Report.Log(ReportLevel.Info, "OpenFile",
                        string.Format("[{0}] Children.Count = 0", parentLabel));
                    return;
                }

                Report.Log(ReportLevel.Info, "OpenFile",
                    string.Format("[{0}] Children.Count = {1}", parentLabel, children.Count));

                for (int i = 0; i < Math.Min(children.Count, 10); i++)
                {
                    var ch = children[i];
                    string cap = SafeAttr(ch, "Caption");
                    string txt = SafeAttr(ch, "Text");
                    string cls = SafeAttr(ch, "ClassName");
                    string aid = SafeAttr(ch, "AutomationId");
                    Report.Log(ReportLevel.Info, "OpenFile",
                        string.Format("[{0}] Child[{1}]: Caption='{2}' Text='{3}' Class='{4}' AutomationId='{5}'",
                            parentLabel, i, cap, txt, cls, aid));
                }
            }
            catch (Exception ex)
            {
                Report.Log(ReportLevel.Info, "OpenFile",
                    string.Format("[{0}] LogChildren exception: {1}", parentLabel, ex.Message));
            }
        }

        private string SafeAttr(Ranorex.Core.Element el, string attr)
        {
            try { return el.GetAttributeValueText(attr) ?? "(null)"; }
            catch { return "(n/a)"; }
        }

    }
}
