///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Lynn_DPI_AT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The OpenFile recording.
    /// </summary>
    [TestModule("a3004660-da32-4050-b6f0-948f53a8bf8f", ModuleType.Recording, 1)]
    public partial class OpenFile : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Lynn_DPI_ATRepository repository.
        /// </summary>
        public static Lynn_DPI_ATRepository repo = Lynn_DPI_ATRepository.Instance;

        static OpenFile instance = new OpenFile();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public OpenFile()
        {
            RecipeFilePath = "C:\\Kohyoung\\Job\\Lynn_20260516_Stacking\\Lynn_Stacking_Underfill.kyjob";
            ExpectedFileName = "Lynn_Stacking_Underfill.kyjob";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static OpenFile Instance
        {
            get { return instance; }
        }

#region Variables

        string _RecipeFilePath;

        /// <summary>
        /// Gets or sets the value of variable RecipeFilePath.
        /// </summary>
        [TestVariable("ec772759-a136-470a-a4dc-d70bcba8dcc6")]
        public string RecipeFilePath
        {
            get { return _RecipeFilePath; }
            set { _RecipeFilePath = value; }
        }

        string _ExpectedFileName;

        /// <summary>
        /// Gets or sets the value of variable ExpectedFileName.
        /// </summary>
        [TestVariable("39058ec5-a0e0-45e8-b26d-b8f070d00d63")]
        public string ExpectedFileName
        {
            get { return _ExpectedFileName; }
            set { _ExpectedFileName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CCIMainWindow.LeftMenuOpenToogleButton' at 22;25.", repo.CCIMainWindow.LeftMenuOpenToogleButtonInfo, new RecordItemIndex(0));
            //repo.CCIMainWindow.LeftMenuOpenToogleButton.Click("22;25");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CCIMainWindow.MenuOpenRecipe' at 73;203.", repo.CCIMainWindow.MenuOpenRecipeInfo, new RecordItemIndex(1));
            //repo.CCIMainWindow.MenuOpenRecipe.Click("73;203");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}o{LControlKey up}'.", new RecordItemIndex(2));
            //Keyboard.Press("{LControlKey down}o{LControlKey up}");
            //Delay.Milliseconds(0);
            
            OpenRecipeFileByPath(RecipeFilePath);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'SelectRecipeFile.Text1148' at 174;11.", repo.SelectRecipeFile.Text1148Info, new RecordItemIndex(4));
            //repo.SelectRecipeFile.Text1148.MoveTo("174;11");
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'SelectRecipeFile.Text1148' at 174;11.", repo.SelectRecipeFile.Text1148Info, new RecordItemIndex(5));
            //repo.SelectRecipeFile.Text1148.MoveTo("174;11");
            //Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Ly' with focus on 'SelectRecipeFile.Text1148'.", repo.SelectRecipeFile.Text1148Info, new RecordItemIndex(6));
            //repo.SelectRecipeFile.Text1148.PressKeys("Ly");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ay{LShiftKey down}_{LShiftKey up}BadMark.ky' with focus on 'SelectRecipeFile.Text1148'.", repo.SelectRecipeFile.Text1148Info, new RecordItemIndex(7));
            //repo.SelectRecipeFile.Text1148.PressKeys("ay{LShiftKey down}_{LShiftKey up}BadMark.ky");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SelectRecipeFile.ButtonOpen' at 39;11.", repo.SelectRecipeFile.ButtonOpenInfo, new RecordItemIndex(8));
            //repo.SelectRecipeFile.ButtonOpen.Click("39;11");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'CCIMainWindow.SomeIndicator'", repo.CCIMainWindow.SomeIndicatorInfo, new ActionTimeout(30000), new RecordItemIndex(9));
            repo.CCIMainWindow.SomeIndicatorInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CCIMainWindow.SomeIndicator' at 1714;196.", repo.CCIMainWindow.SomeIndicatorInfo, new RecordItemIndex(10));
            repo.CCIMainWindow.SomeIndicator.Click("1714;196");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CCIMainWindow.SomeText'.", repo.CCIMainWindow.SomeTextInfo, new RecordItemIndex(11));
            Validate.Exists(repo.CCIMainWindow.SomeTextInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
