///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Lynn_DPI_AT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The OpenFile recording.
    /// </summary>
    [TestModule("a3004660-da32-4050-b6f0-948f53a8bf8f", ModuleType.Recording, 1)]
    public partial class OpenFile : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Lynn_DPI_ATRepository repository.
        /// </summary>
        public static Lynn_DPI_ATRepository repo = Lynn_DPI_ATRepository.Instance;

        static OpenFile instance = new OpenFile();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public OpenFile()
        {
            RecipeFilePath = "C:\\Kohyoung\\Job\\Lynn_20260516_Stacking\\Lynn_Stacking_Underfill.kyjob";
            ExpectedFileName = "Lynn_Stacking_Underfill.kyjob";
            ModelName = "Lynn_Stacking_Underfill";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static OpenFile Instance
        {
            get { return instance; }
        }

#region Variables

        string _RecipeFilePath;

        /// <summary>
        /// Gets or sets the value of variable RecipeFilePath.
        /// </summary>
        [TestVariable("ec772759-a136-470a-a4dc-d70bcba8dcc6")]
        public string RecipeFilePath
        {
            get { return _RecipeFilePath; }
            set { _RecipeFilePath = value; }
        }

        string _ExpectedFileName;

        /// <summary>
        /// Gets or sets the value of variable ExpectedFileName.
        /// </summary>
        [TestVariable("39058ec5-a0e0-45e8-b26d-b8f070d00d63")]
        public string ExpectedFileName
        {
            get { return _ExpectedFileName; }
            set { _ExpectedFileName = value; }
        }

        string _ModelName;

        /// <summary>
        /// Gets or sets the value of variable ModelName.
        /// </summary>
        [TestVariable("c3f81406-c27d-40fb-96f5-1a908854c0b9")]
        public string ModelName
        {
            get { return _ModelName; }
            set { _ModelName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            OpenRecipeFileByPath(RecipeFilePath);
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.CCIMainWindow.Self, false, new RecordItemIndex(1));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
