///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Lynn_DPI_AT
{
    public partial class OpenFile
    {
        // Timeout cho Select Recipe File dialog (ms)
        public const int FILE_DIALOG_TIMEOUT_MS = 30000;

        // Data-driven variables — bind trong Ranorex Studio: Data binding -> RecipeFilePath / ExpectedFileName
        [TestVariable("d4e5f6a7-b8c9-0123-def0-123456789013")]
        public string RecipeFilePath { get; set; }

        [TestVariable("e5f6a7b8-c9d0-1234-ef01-234567890124")]
        public string ExpectedFileName { get; set; }

        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            Report.Log(ReportLevel.Info, "OpenFile",
                string.Format("OpenFile bat dau, RecipeFilePath: '{0}'", RecipeFilePath));
            // NOTE (R3): Init() KHONG the skip recording steps.
            // OpenRecipeFileByPath() phai duoc goi tu User Code Action step trong Ranorex Studio.
        }

        /// <summary>
        /// Mo file recipe bang cach paste full path vao o File name cua dialog.
        /// Goi method nay tu User Code Action step trong recording, sau khi dialog da xuat hien.
        ///
        /// Cach them vao recording (Ranorex Studio, May B):
        ///   1. Disable cac step Text1148 MouseDown/Up, PressKeys, ButtonOpen Click (step 2-6).
        ///   2. Them User Code Action sau step 1 (LeftMenuOpenToogleButton): goi OpenRecipeFileByPath($RecipeFilePath).
        ///   3. Bind column RecipeFilePath tu OpenFileData.csv -> module variable RecipeFilePath.
        ///   4. CSV phai luu bang ANSI (khong dung UTF-8).
        /// </summary>
        public void OpenRecipeFileByPath(string recipeFilePath)
        {
            if (string.IsNullOrEmpty(recipeFilePath))
                throw new ArgumentException("recipeFilePath khong duoc de trong.", "recipeFilePath");

            if (!System.IO.File.Exists(recipeFilePath))
                throw new System.IO.FileNotFoundException(
                    string.Format("File khong ton tai: '{0}'", recipeFilePath), recipeFilePath);

            Report.Log(ReportLevel.Info, "OpenFile",
                string.Format("Cho Select Recipe File dialog (timeout {0}s)...", FILE_DIALOG_TIMEOUT_MS / 1000));

            if (!repo.SelectRecipeFile.SelfInfo.Exists(FILE_DIALOG_TIMEOUT_MS))
                throw new Exception(string.Format(
                    "Select Recipe File dialog khong xuat hien sau {0}s.", FILE_DIALOG_TIMEOUT_MS / 1000));

            repo.SelectRecipeFile.Self.Activate();
            Delay.Milliseconds(300);

            // Focus o File name: Alt+N la standard Windows file dialog shortcut
            Keyboard.Press("{Alt down}n{Alt up}");
            Delay.Milliseconds(500);

            // Select all text hien tai, paste full path qua clipboard
            // Dung clipboard thay vi Keyboard.Press vi path co ky tu dac biet (\, space, _)
            Keyboard.Press("{Control down}a{Control up}");
            Delay.Milliseconds(200);
            WinForms.Clipboard.SetText(recipeFilePath);
            Keyboard.Press("{Control down}v{Control up}");
            Delay.Milliseconds(500);

            Report.Log(ReportLevel.Info, "OpenFile",
                string.Format("Da paste path '{0}' vao File name field.", recipeFilePath));

            Keyboard.Press("{Return}");
            Delay.Milliseconds(500);

            Report.Log(ReportLevel.Success, "OpenFile",
                string.Format("Da press Enter de mo file '{0}'.", recipeFilePath));

            // TODO: Replace with stable validation after recipe file is loaded.
        }

    }
}
