///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Lynn_DPI_AT
{
    public partial class OpenFile_FromProduction
    {
        public const int FILE_DIALOG_TIMEOUT_MS = 15000;
        public const int APPLY_PRESETTING_TIMEOUT_MS = 15000;
        public const int TOP_VALIDATE_TIMEOUT_MS = 60000;
        public const int TOP_VALIDATE_POLL_MS = 2000;

        private void Init()
        {
            Report.Log(ReportLevel.Info, "OpenFile_FromProduction", "Module bat dau.");
            Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                string.Format("Enable = '{0}'", Enable));
            Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                string.Format("RecipeFilePath = '{0}'", RecipeFilePath));
            Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                string.Format("ModelName = '{0}'", ModelName));
        }

        public string OpenRecipeFileByPath()
        {
            if (!string.Equals(this.Enable, "Y", StringComparison.OrdinalIgnoreCase))
            {
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    string.Format("[SKIP] Enable='{0}' — bo qua row nay.", this.Enable));
                return this.RecipeFilePath;
            }

            string recipeFilePath = this.RecipeFilePath;

            if (string.IsNullOrEmpty(recipeFilePath))
                throw new ArgumentException("RecipeFilePath khong duoc de trong.");

            if (!File.Exists(recipeFilePath))
                throw new FileNotFoundException(
                    string.Format("File khong ton tai: '{0}'", recipeFilePath), recipeFilePath);

            Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                string.Format("Target file: '{0}'", recipeFilePath));

            try
            {
                // --- Buoc 1: Click BtnOpenFileFromProduction ---
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    "Buoc 1: Click BtnOpenFileFromProduction...");
                repo.CCIMainWindow.Area1.BtnOpenFileFromProduction.Click();
                Delay.Milliseconds(500);

                // --- Buoc 2: Cho dialog xuat hien ---
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    "Buoc 2: Cho dialog Select Recipe File...");
                if (!repo.SelectRecipeFile.SelfInfo.Exists(FILE_DIALOG_TIMEOUT_MS))
                {
                    Report.Screenshot(repo.CCIMainWindow.Self, true);
                    throw new Exception(
                        "Select Recipe File dialog khong xuat hien sau khi click BtnOpenFileFromProduction.");
                }
                Report.Log(ReportLevel.Success, "OpenFile_FromProduction",
                    "Buoc 2 OK: dialog xuat hien.");

                // --- Buoc 3: Nhap path ---
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction", "Buoc 3: Nhap path...");
                EnterPathIntoFileNameField(recipeFilePath);

                // --- Buoc 4: Click Open ---
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction", "Buoc 4: Click Open...");
                repo.BtnOpenInDialog.Click();
                Delay.Milliseconds(1000);

                // --- Buoc 5: Wait va Click Apply (robust fallback) ---
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    "Buoc 5: Click Apply voi fallback...");
                ClickApplyWithFallback();

                // --- Buoc 6: Cho app load sau Apply ---
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    "Buoc 6: Cho app load sau Apply...");
                Delay.Milliseconds(2000);

                // --- Buoc 7: Validate TopTextRecipeName chua ModelName ---
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    "Buoc 7: Validate ModelName tai vung TOP...");
                ValidateTopModelName();
            }
            finally
            {
                CleanupDialog();
            }

            return this.RecipeFilePath;
        }

        private void EnterPathIntoFileNameField(string path)
        {
            repo.SelectRecipeFile.Self.Activate();
            Delay.Milliseconds(300);
            repo.SelectRecipeFile.Text1148.Click();
            Delay.Milliseconds(300);

            Report.Log(ReportLevel.Info, "OpenFile_FromProduction", "Set TextValue...");
            repo.SelectRecipeFile.Text1148.TextValue = path;
            Delay.Milliseconds(500);

            string fieldText = ReadFileNameField();
            Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                string.Format("Field text: '{0}'", fieldText));

            bool match = !string.IsNullOrEmpty(fieldText)
                && (fieldText.Equals(path, StringComparison.OrdinalIgnoreCase)
                    || path.EndsWith(fieldText, StringComparison.OrdinalIgnoreCase));

            if (!match)
                throw new Exception(string.Format(
                    "Khong the set path. Actual: '{0}', Expected: '{1}'", fieldText, path));

            Report.Log(ReportLevel.Success, "OpenFile_FromProduction",
                string.Format("Path set dung: '{0}'", fieldText));
        }

        private string ReadFileNameField()
        {
            try { return repo.SelectRecipeFile.Text1148.TextValue; }
            catch
            {
                try { return repo.SelectRecipeFile.Text1148.Element.GetAttributeValueText("WindowText"); }
                catch { return "(khong doc duoc)"; }
            }
        }

        private void ValidateTopModelName()
        {
            string expected = this.ModelName;

            if (string.IsNullOrEmpty(expected))
            {
                Report.Log(ReportLevel.Error, "OpenFile_FromProduction",
                    "ModelName is empty. Check ModeName -> ModelName binding in Ranorex Studio.");
                throw new Exception(
                    "ModelName is empty. Check ModeName -> ModelName binding in Ranorex Studio.");
            }

            Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                string.Format("Expected ModelName = '{0}'", expected));

            var sw = System.Diagnostics.Stopwatch.StartNew();
            string actualText = null;

            while (sw.ElapsedMilliseconds < TOP_VALIDATE_TIMEOUT_MS)
            {
                try
                {
                    if (repo.CCIMainWindow.Area1.TopTextRecipeNameInfo.Exists(0))
                    {
                        var el = repo.CCIMainWindow.Area1.TopTextRecipeName.Element;

                        actualText = el.GetAttributeValueText("Text");
                        if (string.IsNullOrEmpty(actualText))
                            actualText = el.GetAttributeValueText("SelectionText");

                        Report.Log(ReportLevel.Debug, "OpenFile_FromProduction",
                            string.Format("ValidateTop poll: Text='{0}' ({1}ms)",
                                actualText ?? "(null)", sw.ElapsedMilliseconds));

                        if (!string.IsNullOrEmpty(actualText) && actualText.Contains(expected))
                        {
                            sw.Stop();
                            Report.Log(ReportLevel.Success, "OpenFile_FromProduction",
                                string.Format("TOP ModelName matched: '{0}' contains '{1}' ({2}ms)",
                                    actualText, expected, sw.ElapsedMilliseconds));
                            return;
                        }
                    }
                }
                catch (Exception ex)
                {
                    Report.Log(ReportLevel.Debug, "OpenFile_FromProduction",
                        string.Format("ValidateTop poll exception: {0}", ex.Message));
                }

                Delay.Milliseconds(TOP_VALIDATE_POLL_MS);
            }

            sw.Stop();
            Report.Screenshot(repo.CCIMainWindow.Self, true);
            Report.Log(ReportLevel.Error, "OpenFile_FromProduction",
                string.Format("TOP ModelName FAIL. Expected contains: '{0}', Actual Text: '{1}' ({2}ms)",
                    expected, actualText ?? "(null)", sw.ElapsedMilliseconds));
            throw new Exception(string.Format(
                "ValidateTopModelName FAIL: TopTextRecipeName Text = '{0}', expected contains '{1}'",
                actualText ?? "(null)", expected));
        }

        private void ClickApplyWithFallback()
        {
            const int DIALOG_CLOSE_WAIT_MS = 30000;

            if (!repo.InspectionRegionSettings.SelfInfo.Exists(APPLY_PRESETTING_TIMEOUT_MS))
            {
                Report.Screenshot(repo.CCIMainWindow.Self, true);
                throw new Exception(string.Format(
                    "Popup dialog khong xuat hien sau {0}ms.", APPLY_PRESETTING_TIMEOUT_MS));
            }
            Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                "Popup dialog da xuat hien. Bat dau click Apply...");

            // Strategy 1: Native WPF Apply — Adapter.Click
            try
            {
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    "Strategy 1: Native WPF Apply.Click()...");
                repo.InspectionRegionSettings.BtnApplyProductionPresetting.Click();
                Delay.Milliseconds(500);
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    string.Format("Strategy 1: cho dialog dong (max {0}ms)...", DIALOG_CLOSE_WAIT_MS));
                if (repo.InspectionRegionSettings.SelfInfo.WaitForNotExists(DIALOG_CLOSE_WAIT_MS))
                {
                    Report.Log(ReportLevel.Success, "OpenFile_FromProduction",
                        "Buoc 5 OK: Apply clicked (Strategy 1 — Native WPF). Dialog da dong.");
                    return;
                }
                Report.Log(ReportLevel.Warn, "OpenFile_FromProduction",
                    "Strategy 1: dialog van con mo sau 30s.");
            }
            catch (Exception ex)
            {
                Report.Log(ReportLevel.Warn, "OpenFile_FromProduction",
                    string.Format("Strategy 1 exception: {0}", ex.Message));
            }

            // Strategy 2: Native WPF Apply — Focus + Space
            try
            {
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    "Strategy 2: Focus + Space...");
                repo.InspectionRegionSettings.BtnApplyProductionPresetting.Focus();
                Delay.Milliseconds(200);
                Keyboard.Press("{Space}");
                Delay.Milliseconds(500);
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    string.Format("Strategy 2: cho dialog dong (max {0}ms)...", DIALOG_CLOSE_WAIT_MS));
                if (repo.InspectionRegionSettings.SelfInfo.WaitForNotExists(DIALOG_CLOSE_WAIT_MS))
                {
                    Report.Log(ReportLevel.Success, "OpenFile_FromProduction",
                        "Buoc 5 OK: Apply clicked (Strategy 2 — Focus+Space). Dialog da dong.");
                    return;
                }
                Report.Log(ReportLevel.Warn, "OpenFile_FromProduction",
                    "Strategy 2: dialog van con mo sau 30s.");
            }
            catch (Exception ex)
            {
                Report.Log(ReportLevel.Warn, "OpenFile_FromProduction",
                    string.Format("Strategy 2 exception: {0}", ex.Message));
            }

            // Strategy 3: UIA BtnApplyProductionPresetting — Click
            try
            {
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    "Strategy 3: UIA BtnApplyProductionPresetting.Click()...");
                if (repo.InspectionRegionSettings.BtnApplyProductionPresettingInfo.Exists(2000))
                {
                    repo.InspectionRegionSettings.BtnApplyProductionPresetting.Click();
                    Delay.Milliseconds(500);
                    Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                        string.Format("Strategy 3: cho dialog dong (max {0}ms)...", DIALOG_CLOSE_WAIT_MS));
                    if (repo.InspectionRegionSettings.SelfInfo.WaitForNotExists(DIALOG_CLOSE_WAIT_MS))
                    {
                        Report.Log(ReportLevel.Success, "OpenFile_FromProduction",
                            "Buoc 5 OK: Apply clicked (Strategy 3 — UIA). Dialog da dong.");
                        return;
                    }
                    Report.Log(ReportLevel.Warn, "OpenFile_FromProduction",
                        "Strategy 3: dialog van con mo sau 30s.");
                }
                else
                {
                    Report.Log(ReportLevel.Warn, "OpenFile_FromProduction",
                        "Strategy 3: BtnApplyProductionPresetting khong tim thay.");
                }
            }
            catch (Exception ex)
            {
                Report.Log(ReportLevel.Warn, "OpenFile_FromProduction",
                    string.Format("Strategy 3 exception: {0}", ex.Message));
            }

            // Strategy 4: Native WPF Apply — Coordinate click via ScreenRectangle
            try
            {
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    "Strategy 4: Coordinate click via ScreenRectangle...");
                var rect = repo.InspectionRegionSettings.BtnApplyProductionPresetting.Element.ScreenRectangle;
                int cx = rect.Location.X + rect.Width / 2;
                int cy = rect.Location.Y + rect.Height / 2;
                Mouse.MoveTo(new Point(cx, cy));
                Mouse.Click();
                Delay.Milliseconds(500);
                Report.Log(ReportLevel.Info, "OpenFile_FromProduction",
                    string.Format("Strategy 4: cho dialog dong (max {0}ms)...", DIALOG_CLOSE_WAIT_MS));
                if (repo.InspectionRegionSettings.SelfInfo.WaitForNotExists(DIALOG_CLOSE_WAIT_MS))
                {
                    Report.Log(ReportLevel.Success, "OpenFile_FromProduction",
                        "Buoc 5 OK: Apply clicked (Strategy 4 — Coordinate). Dialog da dong.");
                    return;
                }
                Report.Log(ReportLevel.Warn, "OpenFile_FromProduction",
                    "Strategy 4: dialog van con mo sau 30s.");
            }
            catch (Exception ex)
            {
                Report.Log(ReportLevel.Warn, "OpenFile_FromProduction",
                    string.Format("Strategy 4 exception: {0}", ex.Message));
            }

            Report.Screenshot(repo.CCIMainWindow.Self, true);
            throw new Exception("Tat ca 4 strategy click Apply deu that bai. Dialog van con mo.");
        }

        private void CleanupDialog()
        {
            try
            {
                if (repo.SelectRecipeFile.SelfInfo.Exists(1000))
                {
                    Report.Log(ReportLevel.Warn, "OpenFile_FromProduction",
                        "CleanupDialog: dialog con mo — dang dong...");
                    Keyboard.Press("{Escape}");
                    Delay.Milliseconds(500);
                    if (repo.SelectRecipeFile.SelfInfo.Exists(1000))
                        repo.SelectRecipeFile.Self.Close();
                }
            }
            catch (Exception ex)
            {
                Report.Log(ReportLevel.Warn, "OpenFile_FromProduction",
                    string.Format("CleanupDialog exception (non-fatal): {0}", ex.Message));
            }
        }

    }
}
