///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Lynn_DPI_AT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The OpenFile_FromProduction recording.
    /// </summary>
    [TestModule("1699bbc7-0bf7-487d-b1e6-ae42362f94ed", ModuleType.Recording, 1)]
    public partial class OpenFile_FromProduction : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Lynn_DPI_ATRepository repository.
        /// </summary>
        public static Lynn_DPI_ATRepository repo = Lynn_DPI_ATRepository.Instance;

        static OpenFile_FromProduction instance = new OpenFile_FromProduction();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public OpenFile_FromProduction()
        {
            Enable = "Y";
            RecipeFilePath = "C:\\Kohyoung\\Job\\Lynn_20260516_Stacking\\Lynn_Stacking_Underfill.kyjob";
            ExpectedFileName = "Lynn_Stacking_Underfill.kyjob";
            ModelName = "Lynn_Stacking_Underfill";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static OpenFile_FromProduction Instance
        {
            get { return instance; }
        }

#region Variables

        string _Enable;

        /// <summary>
        /// Gets or sets the value of variable Enable.
        /// </summary>
        [TestVariable("4cf1d1c7-b805-47e1-9648-0d52ff514235")]
        public string Enable
        {
            get { return _Enable; }
            set { _Enable = value; }
        }

        string _RecipeFilePath;

        /// <summary>
        /// Gets or sets the value of variable RecipeFilePath.
        /// </summary>
        [TestVariable("1c6ffe83-192b-4e2c-98cf-c42d51e4ad9c")]
        public string RecipeFilePath
        {
            get { return _RecipeFilePath; }
            set { _RecipeFilePath = value; }
        }

        string _ExpectedFileName;

        /// <summary>
        /// Gets or sets the value of variable ExpectedFileName.
        /// </summary>
        [TestVariable("f54f5de0-feb9-47c2-870b-196f148b8ae7")]
        public string ExpectedFileName
        {
            get { return _ExpectedFileName; }
            set { _ExpectedFileName = value; }
        }

        string _ModelName;

        /// <summary>
        /// Gets or sets the value of variable ModelName.
        /// </summary>
        [TestVariable("d9113e36-b4f0-48e3-b626-d37b530aa139")]
        public string ModelName
        {
            get { return _ModelName; }
            set { _ModelName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KohyoungGUI1.TabProduction' at 45;5.", repo.KohyoungGUI1.TabProductionInfo, new RecordItemIndex(0));
            repo.KohyoungGUI1.TabProduction.Click("45;5");
            Delay.Milliseconds(0);
            
            RecipeFilePath = OpenRecipeFileByPath();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CCIMainWindow.Area1.BtnOpenFileFromProduction' at 15;19.", repo.CCIMainWindow.Area1.BtnOpenFileFromProductionInfo, new RecordItemIndex(2));
            //repo.CCIMainWindow.Area1.BtnOpenFileFromProduction.Click("15;19");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'SelectRecipeFile.TxtFileNameInDialog' at 111;8.", repo.SelectRecipeFile.TxtFileNameInDialogInfo, new RecordItemIndex(3));
            //repo.SelectRecipeFile.TxtFileNameInDialog.MoveTo("111;8");
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BtnOpenInDialog' at 39;14.", repo.BtnOpenInDialogInfo, new RecordItemIndex(4));
            //repo.BtnOpenInDialog.Click("39;14");
            //Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Success, "User", "", null, false, new RecordItemIndex(5));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
