///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Lynn_DPI_AT
{
    public partial class OpenFile
    {
        public const int FILE_DIALOG_TIMEOUT_MS = 15000;
        public const int DIALOG_CLOSE_TIMEOUT_MS = 5000;

        private void Init()
        {
            Report.Log(ReportLevel.Info, "OpenFile", "OpenFile bat dau.");
            Report.Log(ReportLevel.Info, "OpenFile",
                string.Format("RecipeFilePath = '{0}'", RecipeFilePath));
            Report.Log(ReportLevel.Info, "OpenFile",
                string.Format("ExpectedFileName = '{0}'", ExpectedFileName));
        }

        public void OpenRecipeFileByPath(string recipeFilePath)
        {
            if (string.IsNullOrEmpty(recipeFilePath))
                throw new ArgumentException("recipeFilePath khong duoc de trong.", "recipeFilePath");

            if (!System.IO.File.Exists(recipeFilePath))
                throw new System.IO.FileNotFoundException(
                    string.Format("File khong ton tai tren disk: '{0}'", recipeFilePath), recipeFilePath);

            Report.Log(ReportLevel.Info, "OpenFile",
                string.Format("Target file: '{0}'", recipeFilePath));

            // --- Buoc 1: Verify CCIMainWindow ---
            Report.Log(ReportLevel.Info, "OpenFile", "Buoc 1: Kiem tra CCIMainWindow...");
            if (!repo.CCIMainWindow.SelfInfo.Exists(10000))
                throw new Exception("CCIMainWindow khong ton tai sau 10s.");
            Report.Log(ReportLevel.Success, "OpenFile", "Buoc 1 OK.");

            // --- Buoc 2: Activate ---
            Report.Log(ReportLevel.Info, "OpenFile", "Buoc 2: Activate CCIMainWindow...");
            repo.CCIMainWindow.Self.Activate();
            Delay.Milliseconds(500);
            Report.Log(ReportLevel.Success, "OpenFile", "Buoc 2 OK.");

            // --- Buoc 3: Menu click ---
            Report.Log(ReportLevel.Info, "OpenFile", "Buoc 3: Menu click...");
            repo.CCIMainWindow.LeftMenuOpenToogleButton.Click();
            Delay.Milliseconds(500);
            repo.CCIMainWindow.MenuOpenRecipe.Click();
            Delay.Milliseconds(500);

            if (!repo.SelectRecipeFile.SelfInfo.Exists(FILE_DIALOG_TIMEOUT_MS))
            {
                Report.Log(ReportLevel.Error, "OpenFile", "Buoc 3 THAT BAI: dialog khong xuat hien.");
                throw new Exception("Select Recipe File dialog khong xuat hien.");
            }
            Report.Log(ReportLevel.Success, "OpenFile", "Buoc 3 OK: dialog xuat hien.");

            // --- Buoc 4: Nhap path vao File name ---
            Report.Log(ReportLevel.Info, "OpenFile", "Buoc 4: Nhap path...");
            EnterPathIntoFileNameField(recipeFilePath);

            // --- Buoc 5: Click Open ---
            Report.Log(ReportLevel.Info, "OpenFile", "Buoc 5: Click Open...");
            repo.ButtonOpen.Click();
            Delay.Milliseconds(1000);

            // --- Buoc 6: Verify dialog da dong (file duoc chap nhan) ---
            Report.Log(ReportLevel.Info, "OpenFile", "Buoc 6: Verify dialog da dong...");
            if (repo.SelectRecipeFile.SelfInfo.Exists(DIALOG_CLOSE_TIMEOUT_MS))
            {
                string fieldAfterError = ReadFileNameField();
                Report.Log(ReportLevel.Error, "OpenFile",
                    string.Format("Buoc 6 THAT BAI: dialog van mo. Field text = '{0}'. File co the khong ton tai hoac path sai.", fieldAfterError));

                Keyboard.Press("{Escape}");
                Delay.Milliseconds(500);
                if (repo.SelectRecipeFile.SelfInfo.Exists(1000))
                {
                    Keyboard.Press("{Escape}");
                    Delay.Milliseconds(500);
                }

                throw new Exception(string.Format(
                    "File khong duoc mo. Dialog van hien thi sau khi click Open. Path trong field: '{0}', expected: '{1}'",
                    fieldAfterError, recipeFilePath));
            }
            Report.Log(ReportLevel.Success, "OpenFile",
                string.Format("Buoc 6 OK: Dialog da dong — file '{0}' da duoc chap nhan.", recipeFilePath));
        }

        private void EnterPathIntoFileNameField(string path)
        {
            repo.SelectRecipeFile.Self.Activate();
            Delay.Milliseconds(300);
            repo.SelectRecipeFile.Text1148.Click();
            Delay.Milliseconds(300);

            // Clear field — R1 pattern (proven reliable, khong phu thuoc Ctrl+A)
            Keyboard.Press("{Home}");
            Delay.Milliseconds(50);
            Keyboard.Press("{Shift down}{End}{Shift up}");
            Delay.Milliseconds(50);
            Keyboard.Press("{Delete}");
            Delay.Milliseconds(200);

            // Paste path tu clipboard bang global Keyboard (khong dung element.PressKeys)
            WinForms.Clipboard.SetText(path);
            Delay.Milliseconds(100);
            Keyboard.Press("{LControlKey down}v{LControlKey up}");
            Delay.Milliseconds(500);

            // Verify noi dung field
            string fieldText = ReadFileNameField();
            Report.Log(ReportLevel.Info, "OpenFile",
                string.Format("Field text sau paste: '{0}'", fieldText));

            string expectedName = System.IO.Path.GetFileName(path);
            if (!string.IsNullOrEmpty(fieldText) && fieldText.Contains(expectedName))
            {
                Report.Log(ReportLevel.Success, "OpenFile", "Path nhap dung.");
                return;
            }

            // Retry lan 1: clear va paste lai
            Report.Log(ReportLevel.Warn, "OpenFile",
                string.Format("Field text khong khop (expected chua '{0}'). Retry...", expectedName));

            repo.SelectRecipeFile.Text1148.Click();
            Delay.Milliseconds(200);
            Keyboard.Press("{Home}");
            Delay.Milliseconds(50);
            Keyboard.Press("{Shift down}{End}{Shift up}");
            Delay.Milliseconds(50);
            Keyboard.Press("{Delete}");
            Delay.Milliseconds(200);
            WinForms.Clipboard.SetText(path);
            Delay.Milliseconds(100);
            Keyboard.Press("{LControlKey down}v{LControlKey up}");
            Delay.Milliseconds(800);

            fieldText = ReadFileNameField();
            Report.Log(ReportLevel.Info, "OpenFile",
                string.Format("Retry: field text = '{0}'", fieldText));

            if (string.IsNullOrEmpty(fieldText) || !fieldText.Contains(expectedName))
            {
                Report.Log(ReportLevel.Error, "OpenFile",
                    string.Format("THAT BAI sau retry. Field = '{0}', expected chua '{1}'", fieldText, expectedName));
                throw new Exception(string.Format(
                    "Khong the nhap path vao File name field. Actual: '{0}', Expected chua: '{1}'",
                    fieldText, expectedName));
            }
            Report.Log(ReportLevel.Success, "OpenFile", "Retry OK: path nhap dung.");
        }

        private string ReadFileNameField()
        {
            try
            {
                return repo.SelectRecipeFile.Text1148.TextValue;
            }
            catch
            {
                try
                {
                    return repo.SelectRecipeFile.Text1148.Element.GetAttributeValueText("WindowText");
                }
                catch
                {
                    return "(khong doc duoc)";
                }
            }
        }

        private void Finish()
        {
            if (repo.SelectRecipeFile.SelfInfo.Exists(1000))
            {
                Report.Log(ReportLevel.Warn, "OpenFile", "Finish: dialog con mo — dang dong...");
                Keyboard.Press("{Escape}");
                Delay.Milliseconds(500);
                if (repo.SelectRecipeFile.SelfInfo.Exists(1000))
                    repo.SelectRecipeFile.Self.Close();
            }
        }
    }
}
