///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Lynn_DPI_AT
{
    public partial class RunProduction
    {
        private const int INSPECTION_MAX_TIMEOUT_MS = 36000000;
        private const int NOTICE_POLL_INTERVAL_MS = 5000;
        private const int PROGRESS_LOG_INTERVAL_MS = 60000;
        private const int CLICK_MAX_RETRIES = 3;
        private const int CLICK_ANR_WAIT_MS = 5000;
        private const int CONFIRM_APPEAR_TIMEOUT_MS = 10000;
        private const int LOT_SETTINGS_APPEAR_TIMEOUT_MS = 15000;
        private const int LOT_SETTINGS_CLOSE_TIMEOUT_MS = 10000;
        private const int IDLE_VERIFY_TIMEOUT_MS = 10000;
        private const int POST_CLICK_DELAY_MS = 1000;

        private bool _stepsRanFromInit = false;
        private int _expectedQty;

        private void Init()
        {
            string iqRaw = ProductionContext.LastInspectionQuantity;
            Report.Log(ReportLevel.Info, "RunProduction",
                string.Format("=== BAT DAU RunProduction === InspectionQuantity='{0}' (tu ProductionContext)", iqRaw));

            string iqTrimmed = (iqRaw ?? "").Trim();
            int expectedQty;
            if (string.IsNullOrEmpty(iqTrimmed) || !int.TryParse(iqTrimmed, out expectedQty) || expectedQty <= 0)
            {
                Report.Log(ReportLevel.Error, "RunProduction",
                    string.Format("InspectionQuantity khong hop le: '{0}'. Phai la so nguyen > 0. Kiem tra OpenFile_FromProduction da chay thanh cong voi Enable='Y' chua.", iqRaw));
                throw new ArgumentException(string.Format(
                    "InspectionQuantity khong hop le: '{0}' (tu ProductionContext.LastInspectionQuantity)", iqRaw));
            }

            _expectedQty = expectedQty;
            Report.Log(ReportLevel.Info, "RunProduction",
                string.Format("InspectionQuantity = {0} boards", _expectedQty));

            _stepsRanFromInit = true;
            RunProductionFlow();
        }

        private void RunProductionFlow()
        {
            Step1_ClickRunImpl();
            Step2_WaitForInspectionCompleteImpl();
            Step3_ClickConfirmOnNoticeImpl();
            Step4_ClickCancelOnLotSettingsImpl();
            Step5_VerifyProducedQuantityImpl();
        }

        // === Recording step guards — no-op khi da chay tu Init() ===
        // Auto-generated Run() goi cac method nay SAU Init().
        // Flag _stepsRanFromInit dam bao chung skip ngay, khong chay lai.

        public void Step1_ClickRun()
        {
            if (_stepsRanFromInit)
            {
                Report.Log(ReportLevel.Info, "RunProduction", "Step1: Da chay trong Init(). Skip.");
                return;
            }
            Step1_ClickRunImpl();
        }

        public void Step2_WaitForInspectionComplete()
        {
            if (_stepsRanFromInit)
            {
                Report.Log(ReportLevel.Info, "RunProduction", "Step2: Da chay trong Init(). Skip.");
                return;
            }
            Step2_WaitForInspectionCompleteImpl();
        }

        public void Step3_ClickConfirmOnNotice()
        {
            if (_stepsRanFromInit)
            {
                Report.Log(ReportLevel.Info, "RunProduction", "Step3: Da chay trong Init(). Skip.");
                return;
            }
            Step3_ClickConfirmOnNoticeImpl();
        }

        public void Step4_ClickCancelOnLotSettings()
        {
            if (_stepsRanFromInit)
            {
                Report.Log(ReportLevel.Info, "RunProduction", "Step4: Da chay trong Init(). Skip.");
                return;
            }
            Step4_ClickCancelOnLotSettingsImpl();
        }

        public void Step5_VerifyProducedQuantity(int expectedQty)
        {
            if (_stepsRanFromInit)
            {
                Report.Log(ReportLevel.Info, "RunProduction", "Step5: Da chay trong Init(). Skip.");
                return;
            }
            Step5_VerifyProducedQuantityImpl();
        }

        // === Step implementations ===

        private void Step1_ClickRunImpl()
        {
            Report.Log(ReportLevel.Info, "RunProduction", "Step 1: Click nut Run...");
            ClickWithRetry(() => repo.CCIMainWindow.MainView.BtnRun.Click(), "BtnRun");
            Delay.Milliseconds(POST_CLICK_DELAY_MS);
            Report.Log(ReportLevel.Success, "RunProduction", "Step 1 OK: Da click Run.");
        }

        private void Step2_WaitForInspectionCompleteImpl()
        {
            Report.Log(ReportLevel.Info, "RunProduction",
                string.Format("Step 2: Cho inspection hoan thanh (timeout {0}s, poll moi {1}s)...",
                    INSPECTION_MAX_TIMEOUT_MS / 1000, NOTICE_POLL_INTERVAL_MS / 1000));

            var sw = System.Diagnostics.Stopwatch.StartNew();
            long lastProgressLogMs = 0;

            while (sw.ElapsedMilliseconds < INSPECTION_MAX_TIMEOUT_MS)
            {
                try
                {
                    if (repo.NoticePopup.TxtNoticeInfo.Exists(0))
                    {
                        sw.Stop();
                        Report.Log(ReportLevel.Success, "RunProduction",
                            string.Format("Step 2 OK: Notice popup xuat hien sau {0}s.",
                                sw.ElapsedMilliseconds / 1000));
                        TakeScreenshot();
                        return;
                    }

                    long elapsed = sw.ElapsedMilliseconds;
                    if (elapsed - lastProgressLogMs >= PROGRESS_LOG_INTERVAL_MS)
                    {
                        lastProgressLogMs = elapsed;
                        string progressText = ReadProgressBarText();
                        Report.Log(ReportLevel.Info, "RunProduction",
                            string.Format("Step 2: Dang inspect... Progress={0} ({1}s / {2}s)",
                                progressText, elapsed / 1000, INSPECTION_MAX_TIMEOUT_MS / 1000));
                    }
                }
                catch (Exception ex)
                {
                    if (!ex.GetType().Name.Contains("ApplicationNotResponding"))
                        throw;

                    Report.Log(ReportLevel.Warn, "RunProduction",
                        string.Format("[APP_NOT_RESPONDING] Step 2: App Not Responding ({0}s) — cho {1}ms...",
                            sw.ElapsedMilliseconds / 1000, CLICK_ANR_WAIT_MS));
                    Thread.Sleep(CLICK_ANR_WAIT_MS);
                    continue;
                }

                Delay.Milliseconds(NOTICE_POLL_INTERVAL_MS);
            }

            sw.Stop();
            TakeScreenshot();
            Report.Log(ReportLevel.Failure, "RunProduction",
                string.Format("Step 2 FAIL: Notice popup khong xuat hien sau {0}s.",
                    INSPECTION_MAX_TIMEOUT_MS / 1000));
            throw new TimeoutException(string.Format(
                "Inspection khong hoan thanh trong {0}ms. Notice popup khong xuat hien.",
                INSPECTION_MAX_TIMEOUT_MS));
        }

        private void Step3_ClickConfirmOnNoticeImpl()
        {
            Report.Log(ReportLevel.Info, "RunProduction", "Step 3: Click Confirm tren Notice popup...");

            if (!repo.NoticePopup.ConfirmInfo.Exists(CONFIRM_APPEAR_TIMEOUT_MS))
            {
                TakeScreenshot();
                throw new ElementNotFoundException(
                    "Confirm button khong tim thay tren Notice popup.");
            }

            ClickWithRetry(() => repo.NoticePopup.Confirm.Click(), "NoticePopup.Confirm");
            Delay.Milliseconds(POST_CLICK_DELAY_MS);
            Report.Log(ReportLevel.Success, "RunProduction", "Step 3 OK: Da click Confirm.");
        }

        private void Step4_ClickCancelOnLotSettingsImpl()
        {
            Report.Log(ReportLevel.Info, "RunProduction",
                "Step 4: Cho LOT Settings dialog, click Cancel...");

            if (!repo.KohyoungGUI1.BtnCancelLotSettingsInfo.Exists(LOT_SETTINGS_APPEAR_TIMEOUT_MS))
            {
                TakeScreenshot();
                throw new ElementNotFoundException(
                    "LOT Settings dialog khong xuat hien sau khi click Confirm.");
            }

            Report.Log(ReportLevel.Info, "RunProduction",
                "Step 4: LOT Settings dialog da xuat hien. Click Cancel...");

            ClickWithRetry(() => repo.KohyoungGUI1.BtnCancelLotSettings.Click(), "BtnCancelLotSettings");
            Delay.Milliseconds(POST_CLICK_DELAY_MS);

            var sw = System.Diagnostics.Stopwatch.StartNew();
            while (sw.ElapsedMilliseconds < LOT_SETTINGS_CLOSE_TIMEOUT_MS)
            {
                if (!repo.KohyoungGUI1.BtnCancelLotSettingsInfo.Exists(0))
                {
                    sw.Stop();
                    Report.Log(ReportLevel.Success, "RunProduction",
                        string.Format("Step 4 OK: LOT Settings da dong sau {0}ms.", sw.ElapsedMilliseconds));
                    return;
                }
                Delay.Milliseconds(500);
            }

            sw.Stop();
            TakeScreenshot();
            Report.Log(ReportLevel.Warn, "RunProduction",
                string.Format("Step 4: LOT Settings co the van mo sau {0}ms.", LOT_SETTINGS_CLOSE_TIMEOUT_MS));
        }

        private void Step5_VerifyProducedQuantityImpl()
        {
            Report.Log(ReportLevel.Info, "RunProduction", "Step 5: Verify produced quantity...");
            Delay.Milliseconds(2000);

            string progressText = null;
            var sw = System.Diagnostics.Stopwatch.StartNew();

            while (sw.ElapsedMilliseconds < IDLE_VERIFY_TIMEOUT_MS)
            {
                try
                {
                    progressText = ReadProgressBarText();
                    if (IsProgressValue(progressText))
                        break;
                    progressText = null;
                }
                catch (Exception ex)
                {
                    if (!ex.GetType().Name.Contains("ApplicationNotResponding"))
                        throw;
                    Thread.Sleep(CLICK_ANR_WAIT_MS);
                }
                Delay.Milliseconds(1000);
            }
            sw.Stop();

            if (string.IsNullOrEmpty(progressText))
            {
                TakeScreenshot();
                Report.Log(ReportLevel.Failure, "RunProduction",
                    "Step 5 FAIL: Khong doc duoc gia tri X/Y tu progress bar.");
                return;
            }

            Report.Log(ReportLevel.Info, "RunProduction",
                string.Format("Step 5: Progress bar value = '{0}'", progressText));

            string[] parts = progressText.Split('/');
            int produced;
            if (!int.TryParse(parts[0].Trim(), out produced))
            {
                TakeScreenshot();
                Report.Log(ReportLevel.Failure, "RunProduction",
                    string.Format("Step 5 FAIL: Khong parse duoc so tu '{0}'.", parts[0].Trim()));
                return;
            }

            Report.Log(ReportLevel.Info, "RunProduction",
                string.Format("Step 5: Produced={0}, Expected={1}", produced, _expectedQty));

            if (produced == _expectedQty)
            {
                try { Report.Screenshot(repo.CCIMainWindow.MainView.Self, true); }
                catch { TakeScreenshot(); }

                Report.Log(ReportLevel.Success, "RunProduction",
                    string.Format("Step 5 PASS: Produced={0} khop voi InspectionQuantity={1}. Progress: {2}",
                        produced, _expectedQty, progressText));
            }
            else
            {
                try { Report.Screenshot(repo.CCIMainWindow.MainView.Self, true); }
                catch { TakeScreenshot(); }

                Report.Log(ReportLevel.Failure, "RunProduction",
                    string.Format("Step 5 FAIL: Produced={0} KHONG khop voi InspectionQuantity={1}. Progress: {2}",
                        produced, _expectedQty, progressText));
            }
        }

        // === Helpers ===

        private void ClickWithRetry(Action clickAction, string elementName)
        {
            Exception lastEx = null;
            for (int attempt = 0; attempt <= CLICK_MAX_RETRIES; attempt++)
            {
                try
                {
                    if (attempt > 0)
                        Report.Log(ReportLevel.Info, "RunProduction",
                            string.Format("Retry {0}/{1} cho {2}...", attempt, CLICK_MAX_RETRIES, elementName));
                    clickAction();
                    return;
                }
                catch (Exception ex)
                {
                    lastEx = ex;
                    if (!ex.GetType().Name.Contains("ApplicationNotResponding"))
                        throw;
                    Report.Log(ReportLevel.Warn, "RunProduction",
                        string.Format("[APP_NOT_RESPONDING] {0} attempt {1} — cho {2}ms...",
                            elementName, attempt + 1, CLICK_ANR_WAIT_MS));
                    if (attempt < CLICK_MAX_RETRIES)
                        Thread.Sleep(CLICK_ANR_WAIT_MS);
                }
            }
            Report.Log(ReportLevel.Error, "RunProduction",
                string.Format("{0}: FAIL sau {1} attempts.", elementName, CLICK_MAX_RETRIES + 1));
            throw lastEx;
        }

        private string ReadProgressBarText()
        {
            try
            {
                // Approach 1: TxtProducedQty — thu Text truoc, Caption sau (lesson WPF Caption vs Text)
                if (repo.CCIMainWindow.MainView.TxtProducedQtyInfo.Exists(0))
                {
                    var el = repo.CCIMainWindow.MainView.TxtProducedQty.Element;

                    string text = SafeReadAttribute(el, "Text");
                    if (IsProgressValue(text))
                        return text.Trim();

                    string caption = SafeReadAttribute(el, "Caption");
                    if (IsProgressValue(caption))
                        return caption.Trim();
                }

                // Approach 2: ProgressBar element attributes
                if (repo.CCIMainWindow.MainView.ProgressBarInfo.Exists(0))
                {
                    var pbEl = repo.CCIMainWindow.MainView.ProgressBar.Element;
                    foreach (string attr in new[] { "Text", "Caption", "AccessibleValue" })
                    {
                        string val = SafeReadAttribute(pbEl, attr);
                        if (IsProgressValue(val))
                            return val.Trim();
                    }

                    // Approach 3: Tim tat ca text children cua progressbar
                    try
                    {
                        IList<Ranorex.Text> texts =
                            repo.CCIMainWindow.MainView.ProgressBar.Find<Ranorex.Text>(".//text");
                        foreach (var txt in texts)
                        {
                            foreach (string attr in new[] { "Text", "Caption" })
                            {
                                string val = SafeReadAttribute(txt.Element, attr);
                                if (IsProgressValue(val))
                                    return val.Trim();
                            }
                        }
                    }
                    catch { }
                }

                return "(no X/Y found)";
            }
            catch
            {
                return "(read error)";
            }
        }

        private bool IsProgressValue(string val)
        {
            return !string.IsNullOrEmpty(val) && Regex.IsMatch(val, @"\d+\s*/\s*\d+");
        }

        private string SafeReadAttribute(Ranorex.Core.Element el, string attr)
        {
            try { return el.GetAttributeValueText(attr); }
            catch { return null; }
        }

        private void TakeScreenshot()
        {
            try { Report.Screenshot(repo.CCIMainWindow.Self, true); }
            catch { try { Report.Screenshot(); } catch { } }
        }
    }
}
