///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Lynn_DPI_AT
{
    public partial class Verify_ProductionPresettingDialog_AutoClose
    {
        private const int DIALOG_APPEAR_TIMEOUT_MS = 10000;
        private const int DIALOG_AUTOCLOSE_TIMEOUT_MS = 30000;
        private const int POLL_INTERVAL_MS = 500;

        private void Init()
        {
            Report.Log(ReportLevel.Info, "VerifyAutoClose", "Module bat dau — verify dialog Production Presetting tu dong dong.");
        }

        public void ClickApplyWithPolling()
        {
            var sw = System.Diagnostics.Stopwatch.StartNew();

            // BUOC 1: Cho dialog xuat hien
            Report.Log(ReportLevel.Info, "VerifyAutoClose",
                string.Format("BUOC 1: Cho dialog 'Production Presetting' xuat hien (toi da {0}s)...",
                    DIALOG_APPEAR_TIMEOUT_MS / 1000));

            bool appeared = false;
            while (sw.ElapsedMilliseconds < DIALOG_APPEAR_TIMEOUT_MS)
            {
                if (repo.InspectionRegionSettings.SelfInfo.Exists(0))
                {
                    appeared = true;
                    break;
                }
                Delay.Milliseconds(POLL_INTERVAL_MS);
            }

            if (!appeared)
            {
                sw.Stop();
                Report.Log(ReportLevel.Failure, "VerifyAutoClose",
                    string.Format("THAT BAI: Dialog khong xuat hien sau {0}s. App khong hien thi dialog nhu mong doi.",
                        DIALOG_APPEAR_TIMEOUT_MS / 1000));
                throw new Exception(string.Format(
                    "VerifyAutoClose: Dialog 'Production Presetting' khong xuat hien sau {0}s.",
                    DIALOG_APPEAR_TIMEOUT_MS / 1000));
            }

            Report.Log(ReportLevel.Success, "VerifyAutoClose",
                string.Format("Dialog da xuat hien sau {0:F1}s.", sw.ElapsedMilliseconds / 1000.0));

            // BUOC 2: Cho dialog tu dong dong
            sw.Restart();
            Report.Log(ReportLevel.Info, "VerifyAutoClose",
                string.Format("BUOC 2: Cho dialog tu dong dong (toi da {0}s)...",
                    DIALOG_AUTOCLOSE_TIMEOUT_MS / 1000));

            bool closed = false;
            while (sw.ElapsedMilliseconds < DIALOG_AUTOCLOSE_TIMEOUT_MS)
            {
                if (!repo.InspectionRegionSettings.SelfInfo.Exists(0))
                {
                    closed = true;
                    break;
                }
                Delay.Milliseconds(POLL_INTERVAL_MS);
            }
            sw.Stop();

            if (!closed)
            {
                try { Report.Screenshot(repo.InspectionRegionSettings.Self, true); }
                catch { try { Report.Screenshot(); } catch { } }

                Report.Log(ReportLevel.Failure, "VerifyAutoClose",
                    string.Format("THAT BAI: Dialog van con mo sau {0}s. App khong tu dong dong dialog.",
                        DIALOG_AUTOCLOSE_TIMEOUT_MS / 1000));
                throw new Exception(string.Format(
                    "VerifyAutoClose: Dialog 'Production Presetting' khong tu dong dong sau {0}s. Kiem tra app co bi treo hoac loading qua lau.",
                    DIALOG_AUTOCLOSE_TIMEOUT_MS / 1000));
            }

            Report.Log(ReportLevel.Success, "VerifyAutoClose",
                string.Format("Dialog da tu dong sau {0:F1}s — TEST PASS.", sw.ElapsedMilliseconds / 1000.0));
        }
    }
}
