///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Lynn_DPI_AT
{
    public partial class Verify_ProductionPresettingDialog_AutoClose
    {
        private const int DIALOG_APPEAR_TIMEOUT_MS = 15000;
        private const int DIALOG_AUTOCLOSE_TIMEOUT_MS = 30000;
        private const int APPLY_ENABLED_TIMEOUT_MS = 10000;
        private const int APPLY_CLOSE_VERIFY_TIMEOUT_MS = 90000;
        private const int POLL_INTERVAL_MS = 500;

        private void Init()
        {
            Report.Log(ReportLevel.Info, "VerifyAutoClose", "Module bat dau — verify dialog Production Presetting tu dong dong.");
        }

        public void ClickApplyWithPolling()
        {
            var sw = System.Diagnostics.Stopwatch.StartNew();

            // === BUOC 1: Cho dialog xuat hien (max 15s) ===
            Report.Log(ReportLevel.Info, "VerifyAutoClose",
                string.Format("BUOC 1: Cho dialog 'Production Presetting' xuat hien (toi da {0}s)...",
                    DIALOG_APPEAR_TIMEOUT_MS / 1000));

            bool appeared = repo.InspectionRegionSettings.SelfInfo.Exists(DIALOG_APPEAR_TIMEOUT_MS);

            if (!appeared)
            {
                sw.Stop();
                Report.Log(ReportLevel.Failure, "VerifyAutoClose",
                    string.Format("THAT BAI: Dialog khong xuat hien sau {0}s. App khong hien thi dialog nhu mong doi.",
                        DIALOG_APPEAR_TIMEOUT_MS / 1000));
                throw new Exception(string.Format(
                    "VerifyAutoClose: Dialog 'Production Presetting' khong xuat hien sau {0}s.",
                    DIALOG_APPEAR_TIMEOUT_MS / 1000));
            }

            Report.Log(ReportLevel.Success, "VerifyAutoClose",
                string.Format("Dialog da xuat hien sau {0:F1}s.", sw.ElapsedMilliseconds / 1000.0));

            // === BUOC 2: Cho dialog tu dong dong (max 30s) ===
            sw.Restart();
            Report.Log(ReportLevel.Info, "VerifyAutoClose",
                string.Format("BUOC 2: Cho dialog tu dong dong (toi da {0}s)...",
                    DIALOG_AUTOCLOSE_TIMEOUT_MS / 1000));

            try
            {
                repo.InspectionRegionSettings.BtnApplyProductionPresettingInfo.WaitForNotExists(DIALOG_AUTOCLOSE_TIMEOUT_MS);
                sw.Stop();
                Report.Log(ReportLevel.Success, "VerifyAutoClose",
                    string.Format("Dialog da tu dong dong sau {0:F1}s — TEST PASS (hanh vi dung).",
                        sw.ElapsedMilliseconds / 1000.0));
                return;
            }
            catch
            {
                sw.Stop();
            }

            // === BUOC 3: FALLBACK — dialog khong tu dong dong, thu click Apply ===
            Report.Log(ReportLevel.Warn, "VerifyAutoClose",
                string.Format("Dialog KHONG tu dong dong sau {0}s. Chuyen sang fallback: click Apply.",
                    DIALOG_AUTOCLOSE_TIMEOUT_MS / 1000));

            // 3a: Cho Apply button enabled (max 10s)
            sw.Restart();
            Report.Log(ReportLevel.Info, "VerifyAutoClose",
                string.Format("BUOC 3: FALLBACK — cho Apply button enabled (toi da {0}s)...",
                    APPLY_ENABLED_TIMEOUT_MS / 1000));

            bool applyClicked = false;
            while (sw.ElapsedMilliseconds < APPLY_ENABLED_TIMEOUT_MS)
            {
                try
                {
                    var btnInfo = repo.InspectionRegionSettings.BtnApplyProductionPresettingInfo;
                    if (btnInfo.Exists(0))
                    {
                        var btn = repo.InspectionRegionSettings.BtnApplyProductionPresetting;
                        if (btn.Visible && btn.Enabled)
                        {
                            Report.Log(ReportLevel.Info, "VerifyAutoClose",
                                string.Format("Apply button da enabled sau {0:F1}s — click Apply.",
                                    sw.ElapsedMilliseconds / 1000.0));
                            btn.Click();
                            applyClicked = true;
                            break;
                        }
                    }
                }
                catch (Exception ex)
                {
                    Report.Log(ReportLevel.Warn, "VerifyAutoClose",
                        string.Format("Loi khi kiem tra Apply button: {0}", ex.Message));
                }
                Delay.Milliseconds(POLL_INTERVAL_MS);
            }
            sw.Stop();

            if (!applyClicked)
            {
                TakeScreenshot();
                Report.Log(ReportLevel.Failure, "VerifyAutoClose",
                    string.Format("THAT BAI: Apply button khong enabled sau {0}s. Dialog bi treo.",
                        APPLY_ENABLED_TIMEOUT_MS / 1000));
                throw new Exception(string.Format(
                    "VerifyAutoClose: Dialog khong tu dong dong va Apply button khong enabled sau {0}s.",
                    APPLY_ENABLED_TIMEOUT_MS / 1000));
            }

            // 3b: Verify dialog dong sau click Apply
            sw.Restart();
            LogDiagElementState("TRUOC_WAIT");
            try
            {
                repo.InspectionRegionSettings.BtnApplyProductionPresettingInfo.WaitForNotExists(APPLY_CLOSE_VERIFY_TIMEOUT_MS);
            }
            catch
            {
                sw.Stop();
                LogDiagElementState("SAU_WAIT_FAIL");
                TakeScreenshot();
                Report.Log(ReportLevel.Failure, "VerifyAutoClose",
                    string.Format("THAT BAI: Dialog van con mo sau khi click Apply ({0}s). App loi nghiem trong.",
                        APPLY_CLOSE_VERIFY_TIMEOUT_MS / 1000));
                throw new Exception(string.Format(
                    "VerifyAutoClose: Dialog khong dong sau khi click Apply ({0}s).",
                    APPLY_CLOSE_VERIFY_TIMEOUT_MS / 1000));
            }
            sw.Stop();

            Report.Log(ReportLevel.Warn, "VerifyAutoClose",
                string.Format("Dialog da dong sau khi click Apply ({0:F1}s). "
                    + "TEST PASS nhung app KHONG tu dong dong dialog — can review lai.",
                    sw.ElapsedMilliseconds / 1000.0));
        }

        private void LogDiagElementState(string label)
        {
            const string DIALOG_RXPATH = "/form[@name='Popup' and @title='Production Presetting']";
            const string BUTTON_RXPATH = DIALOG_RXPATH + "/.//button[@text='Apply']";

            try
            {
                Report.Log(ReportLevel.Info, "DIAG",
                    string.Format("=== DIAG [{0}] BAT DAU ===", label));

                // 1. Dem so form match dialog path
                var forms = Host.Local.Find<Ranorex.Form>(DIALOG_RXPATH);
                Report.Log(ReportLevel.Info, "DIAG",
                    string.Format("[{0}] So form match dialog path: {1}", label, forms.Count));

                for (int i = 0; i < forms.Count; i++)
                {
                    try
                    {
                        var f = forms[i];
                        var rect = f.Element.ScreenRectangle;
                        Report.Log(ReportLevel.Info, "DIAG",
                            string.Format("[{0}] Form[{1}]: Visible={2}, Enabled={3}, Rect={4}, Path={5}",
                                label, i, f.Visible, f.Enabled,
                                string.Format("({0},{1},{2},{3})", rect.X, rect.Y, rect.Width, rect.Height),
                                f.Element.ToString()));
                    }
                    catch (Exception ex)
                    {
                        Report.Log(ReportLevel.Warn, "DIAG",
                            string.Format("[{0}] Form[{1}]: LOI doc properties — {2}", label, i, ex.Message));
                    }
                }

                // 2. Dem so button match Apply path (direct find)
                var buttons = Host.Local.Find<Ranorex.Button>(BUTTON_RXPATH);
                Report.Log(ReportLevel.Info, "DIAG",
                    string.Format("[{0}] So button match Apply path (direct): {1}", label, buttons.Count));

                for (int i = 0; i < buttons.Count; i++)
                {
                    try
                    {
                        var b = buttons[i];
                        var rect = b.Element.ScreenRectangle;
                        Report.Log(ReportLevel.Info, "DIAG",
                            string.Format("[{0}] Button[{1}]: Visible={2}, Enabled={3}, Rect={4}",
                                label, i, b.Visible, b.Enabled,
                                string.Format("({0},{1},{2},{3})", rect.X, rect.Y, rect.Width, rect.Height)));
                    }
                    catch (Exception ex)
                    {
                        Report.Log(ReportLevel.Warn, "DIAG",
                            string.Format("[{0}] Button[{1}]: LOI doc properties — {2}", label, i, ex.Message));
                    }
                }

                // 3. Repo accessor — kiem tra stale cache
                bool repoExists = repo.InspectionRegionSettings.BtnApplyProductionPresettingInfo.Exists(0);
                Report.Log(ReportLevel.Info, "DIAG",
                    string.Format("[{0}] Repo BtnApply Exists(0): {1}", label, repoExists));

                if (repoExists)
                {
                    try
                    {
                        var repoBtn = repo.InspectionRegionSettings.BtnApplyProductionPresetting;
                        var repoRect = repoBtn.Element.ScreenRectangle;
                        Report.Log(ReportLevel.Info, "DIAG",
                            string.Format("[{0}] Repo BtnApply: Visible={1}, Enabled={2}, Rect=({3},{4},{5},{6})",
                                label, repoBtn.Visible, repoBtn.Enabled,
                                repoRect.X, repoRect.Y, repoRect.Width, repoRect.Height));
                    }
                    catch (Exception ex)
                    {
                        Report.Log(ReportLevel.Warn, "DIAG",
                            string.Format("[{0}] Repo BtnApply: LOI doc properties — {1}", label, ex.Message));
                    }
                }

                Report.Log(ReportLevel.Info, "DIAG",
                    string.Format("=== DIAG [{0}] KET THUC ===", label));
            }
            catch (Exception ex)
            {
                Report.Log(ReportLevel.Warn, "DIAG",
                    string.Format("[{0}] DIAG LOI TONG: {1}", label, ex.Message));
            }
        }

        private void TakeScreenshot()
        {
            try { Report.Screenshot(repo.InspectionRegionSettings.Self, true); }
            catch { try { Report.Screenshot(); } catch { } }
        }
    }
}
